-- ============================================================================
-- V1: MySQL 迁移全量基线（2026-08-30 PG→MySQL 迁移，由线上 PG 库反向生成）
--
-- 来源：线上 Supabase PG 17.6（public schema，pg_dump --schema-only 导出后转换）
-- 转换：/tmp/pg2mysql.py（转换规则见 docs/pg-to-mysql-migration-analysis.md）
-- 策略：MySQL 环境放弃逐脚本翻译（V1-V61 为 PG 方言），全新库直接执行本基线
--       即达最新结构；数据从线上 PG pg_dump → 类型映射 → mysql load 搬运。
--
-- 关键转换决策：
-- 1. bigint GENERATED BY DEFAULT AS IDENTITY → bigint AUTO_INCREMENT，主键内联
--    PRIMARY KEY (id)（MySQL 要求 AUTO_INCREMENT 列必须为 key；本项目全表单列主键）
-- 2. boolean → tinyint(1)；timestamp without time zone → datetime(6)；double precision → double
-- 3. 部分唯一索引（PG WHERE 谓词）→ 生成列 uk_key_<idx> = IF(cond, MD5(...), NULL) STORED
--    + UNIQUE KEY——精确复刻语义：条件不满足行生成列=NULL 不受唯一约束
--    （MySQL UNIQUE 允许多个 NULL）。涉及表：venue_crowd_reports / venue_claims /
--    venue_feedbacks×2 / points_gates / points_transactions / dancer_services / tag_dict。
--    「单列 IS NOT NULL」形态（demand_records.rescue_origin）→ 全量 UNIQUE（语义等价）。
--    非唯一部分索引 → 全量索引（性能等价）。
-- 4. qwt_city_key(text) PG 函数 → MySQL DETERMINISTIC 函数（LEFT(city,-1)→LEFT(city,LENGTH(city)-1)）
-- 5. 保留字列名反引号：qwt_ops_config.key（MySQL KEY 保留字）
-- ============================================================================

-- Name: public; Type: SCHEMA; Schema: -; Owner: -
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
-- Name: qwt_city_key(text); Type: FUNCTION; Schema: public; Owner: -
-- qwt_city_key: 城市名规范化（去「市」后缀），供 native SQL 使用（DancerRepository）
CREATE FUNCTION qwt_city_key(city TEXT) RETURNS TEXT DETERMINISTIC
RETURN CASE WHEN RIGHT(city, 1) = '市' THEN LEFT(city, LENGTH(city) - 1) ELSE city END;

-- Name: anonymous_quotas; Type: TABLE; Schema: public; Owner: -
-- Name: conversation_messages; Type: TABLE; Schema: public; Owner: -
-- Name: conversations; Type: TABLE; Schema: public; Owner: -
-- Name: device_authorizations; Type: TABLE; Schema: public; Owner: -
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
-- Name: marketplace_categories; Type: TABLE; Schema: public; Owner: -
-- Name: marketplace_installs; Type: TABLE; Schema: public; Owner: -
-- Name: marketplace_items; Type: TABLE; Schema: public; Owner: -
-- Name: marketplace_ratings; Type: TABLE; Schema: public; Owner: -
-- Name: marketplace_registries; Type: TABLE; Schema: public; Owner: -
-- Name: mcp_server_configs; Type: TABLE; Schema: public; Owner: -
-- Name: model_catalog; Type: TABLE; Schema: public; Owner: -
-- Name: model_catalog_unknown_observations; Type: TABLE; Schema: public; Owner: -
-- Name: push_notification_contents; Type: TABLE; Schema: public; Owner: -
-- Name: qwt_app_feedbacks; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_app_feedbacks (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) NOT NULL,
    user_id bigint,
    category varchar(20) NOT NULL,
    content varchar(500) NOT NULL,
    image_url varchar(512),
    status varchar(20) DEFAULT 'PENDING' NOT NULL,
    handled_by bigint,
    handled_at datetime(6),
    handle_note varchar(500),
    PRIMARY KEY (id)
);

-- Name: qwt_app_feedbacks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_daily_checkins; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_daily_checkins (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    user_id bigint NOT NULL,
    checkin_date date NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_daily_checkins_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancer_ad_views; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancer_ad_views (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    dancer_id bigint NOT NULL,
    user_id bigint NOT NULL,
    view_date date NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_dancer_ad_views_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancer_cities; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancer_cities (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) DEFAULT false NOT NULL,
    dancer_id bigint NOT NULL,
    city varchar(50) NOT NULL,
    sort_order int DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_dancer_cities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancer_favorites; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancer_favorites (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) DEFAULT false NOT NULL,
    user_id bigint NOT NULL,
    dancer_id bigint NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_dancer_favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancer_photos; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancer_photos (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) NOT NULL,
    dancer_id bigint NOT NULL,
    url varchar(500) NOT NULL,
    status varchar(20) DEFAULT 'PENDING' NOT NULL,
    created_by bigint NOT NULL,
    sort_order int DEFAULT 0 NOT NULL,
    blur_url varchar(500),
    kind varchar(10) DEFAULT 'PHOTO' NOT NULL,
    cover_url varchar(500),
    duration_seconds int DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_dancer_photos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancer_recognition_tags; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancer_recognition_tags (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6) NOT NULL,
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6) NOT NULL,
    dancer_id bigint NOT NULL,
    recognition_id bigint NOT NULL,
    tag varchar(50) NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_dancer_recognition_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancer_recognitions; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancer_recognitions (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6) NOT NULL,
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6) NOT NULL,
    dancer_id bigint NOT NULL,
    recognition_date date NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_dancer_recognitions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancer_services; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancer_services (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) DEFAULT false NOT NULL,
    dancer_id bigint NOT NULL,
    label varchar(20) NOT NULL,
    category varchar(20) NOT NULL,
    price_text varchar(100) DEFAULT '' NOT NULL,
    location_scope varchar(100) DEFAULT '' NOT NULL,
    advance_notice varchar(100) DEFAULT '' NOT NULL,
    rules varchar(300) DEFAULT '' NOT NULL,
    sort_order int DEFAULT 0 NOT NULL,
    active tinyint(1) DEFAULT true NOT NULL,
    sub_category varchar(100),
    negotiable tinyint(1) DEFAULT true NOT NULL,
    uk_key_uk_qwt_dancer_services_dancer_label varchar(32) GENERATED ALWAYS AS (IF((deleted = 0), MD5(CONCAT_WS('#', COALESCE(CAST(dancer_id AS CHAR), '<n>'), COALESCE(CAST(label AS CHAR), '<n>'))), NULL)) STORED,
    PRIMARY KEY (id)
);

-- Name: qwt_dancer_services_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancer_shares; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancer_shares (
    id bigint NOT NULL AUTO_INCREMENT,
    dancer_id bigint NOT NULL,
    user_id bigint,
    event_type varchar(16) NOT NULL,
    channel varchar(16),
    share_from bigint,
    created_at datetime(6),
    PRIMARY KEY (id)
);

-- Name: qwt_dancer_shares_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancer_venues; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancer_venues (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6) NOT NULL,
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6) NOT NULL,
    dancer_id bigint NOT NULL,
    note varchar(200),
    relation varchar(20) NOT NULL,
    venue_id bigint NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_dancer_venues_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancer_verification_logs; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancer_verification_logs (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    dancer_id bigint NOT NULL,
    operator_id bigint,
    from_status varchar(20) NOT NULL,
    to_status varchar(20) NOT NULL,
    reason varchar(200),
    PRIMARY KEY (id)
);

-- Name: qwt_dancer_verification_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancer_views; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancer_views (
    id bigint NOT NULL AUTO_INCREMENT,
    dancer_id bigint NOT NULL,
    user_id bigint,
    view_date date NOT NULL,
    source varchar(16) DEFAULT 'OTHER' NOT NULL,
    created_at datetime(6),
    PRIMARY KEY (id)
);

-- Name: qwt_dancer_views_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_dancers; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_dancers (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6) NOT NULL,
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6) NOT NULL,
    avatar_url varchar(500),
    bio varchar(300),
    city varchar(50),
    created_by bigint NOT NULL,
    gender varchar(20),
    nickname varchar(30) NOT NULL,
    status varchar(20) DEFAULT 'PENDING' NOT NULL,
    contact varchar(100),
    earnings_enabled tinyint(1) DEFAULT false NOT NULL,
    verification_status varchar(20) DEFAULT 'UNVERIFIED' NOT NULL,
    verified_at datetime(6),
    verified_by bigint,
    hide_contact tinyint(1) DEFAULT true NOT NULL,
    contact_image_url varchar(500),
    profile_tags varchar(500),
    require_user_location tinyint(1) DEFAULT false NOT NULL,
    current_city varchar(50),
    contact_relay tinyint(1) DEFAULT false NOT NULL,
    auto_release tinyint(1) DEFAULT true NOT NULL,
    contact_updated_at datetime(6),
    PRIMARY KEY (id)
);

-- Name: qwt_dancers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_demand_records; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_demand_records (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    user_id bigint NOT NULL,
    dancer_id bigint NOT NULL,
    service_ids varchar(100) NOT NULL,
    time_slots varchar(50) NOT NULL,
    duration varchar(20),
    message varchar(120) DEFAULT '' NOT NULL,
    user_location varchar(20),
    status varchar(20),
    fulfilled_at datetime(6),
    reject_reason varchar(20),
    rescue_requested_at datetime(6),
    origin_demand_id bigint,
    share_opened_at datetime(6),
    guest_feedback varchar(20),
    feedback_requested_at datetime(6),
    guest_feedback_handled_at datetime(6),
    PRIMARY KEY (id)
);

-- Name: qwt_demand_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_favorites; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_favorites (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6),
    user_id bigint NOT NULL,
    venue_id bigint NOT NULL,
    unfavorited_at datetime(6),
    PRIMARY KEY (id)
);

-- Name: qwt_favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_flyway_schema_history; Type: TABLE; Schema: public; Owner: -
-- (skipped: qwt_flyway_schema_history — Flyway 自建表)

-- Name: qwt_group_chats; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_group_chats (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) DEFAULT false NOT NULL,
    name varchar(64) NOT NULL,
    scope varchar(20) NOT NULL,
    city varchar(50),
    region varchar(50),
    qr_code_url varchar(500) NOT NULL,
    description varchar(200),
    display_order int DEFAULT 0 NOT NULL,
    enabled tinyint(1) DEFAULT true NOT NULL,
    updated_by bigint,
    PRIMARY KEY (id)
);

-- Name: qwt_group_chats_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_messages; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_messages (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) NOT NULL,
    user_id bigint NOT NULL,
    type varchar(30) NOT NULL,
    title varchar(100) NOT NULL,
    content varchar(500) NOT NULL,
    related_type varchar(30),
    related_id bigint,
    read_at datetime(6),
    PRIMARY KEY (id)
);

-- Name: qwt_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_ops_config; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_ops_config (
    id bigint NOT NULL AUTO_INCREMENT,
    `key` varchar(64) NOT NULL,
    value varchar(255) NOT NULL,
    updated_by bigint,
    updated_at datetime(6),
    PRIMARY KEY (id)
);

-- Name: qwt_ops_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_points_accounts; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_points_accounts (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    user_id bigint NOT NULL,
    balance bigint DEFAULT 0 NOT NULL,
    earned_total bigint DEFAULT 0 NOT NULL,
    spent_total bigint DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_points_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_points_gates; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_points_gates (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) NOT NULL,
    target_type varchar(30) NOT NULL,
    target_id bigint NOT NULL,
    cost int NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint,
    uk_key_qwt_uk_points_gates_target varchar(32) GENERATED ALWAYS AS (IF((deleted = 0), MD5(CONCAT_WS('#', COALESCE(CAST(target_type AS CHAR), '<n>'), COALESCE(CAST(target_id AS CHAR), '<n>'))), NULL)) STORED,
    PRIMARY KEY (id)
);

-- Name: qwt_points_gates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_points_transactions; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_points_transactions (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    user_id bigint NOT NULL,
    delta bigint NOT NULL,
    balance_after bigint NOT NULL,
    source_type varchar(30) NOT NULL,
    source_id bigint,
    target_type varchar(20),
    target_id bigint,
    remark varchar(200),
    gift_code varchar(30),
    uk_key_qwt_uk_pts_tx_earn_dedup varchar(32) GENERATED ALWAYS AS (IF(((delta > 0) AND (source_id IS NOT NULL)), MD5(CONCAT_WS('#', COALESCE(CAST(user_id AS CHAR), '<n>'), COALESCE(CAST(source_type AS CHAR), '<n>'), COALESCE(CAST(source_id AS CHAR), '<n>'))), NULL)) STORED,
    PRIMARY KEY (id)
);

-- Name: qwt_points_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_points_unlocks; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_points_unlocks (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    user_id bigint NOT NULL,
    target_type varchar(30) NOT NULL,
    target_id bigint NOT NULL,
    transaction_id bigint,
    PRIMARY KEY (id)
);

-- Name: qwt_points_unlocks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_recruitment_contacts; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_recruitment_contacts (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) NOT NULL,
    recruitment_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_recruitment_contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_recruitments; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_recruitments (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) NOT NULL,
    venue_id bigint NOT NULL,
    position_types varchar(200) NOT NULL,
    headcount int,
    term varchar(20) DEFAULT 'LONG_TERM' NOT NULL,
    gender_limit varchar(10) DEFAULT 'ANY' NOT NULL,
    age_min int,
    age_max int,
    salary_type varchar(20) DEFAULT 'NEGOTIABLE' NOT NULL,
    salary_text varchar(64),
    accommodation tinyint(1),
    travel_paid tinyint(1),
    description varchar(1000) NOT NULL,
    contact_name varchar(32),
    contact_phone varchar(20),
    contact_wechat varchar(64),
    is_urgent tinyint(1) DEFAULT false NOT NULL,
    status varchar(20) DEFAULT 'DRAFT' NOT NULL,
    published_at datetime(6),
    expires_at datetime(6) NOT NULL,
    created_by bigint NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_recruitments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_tag_dict; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_tag_dict (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) DEFAULT false NOT NULL,
    scope varchar(20) NOT NULL,
    text varchar(20) NOT NULL,
    description varchar(300) DEFAULT '' NOT NULL,
    sort_order int DEFAULT 0 NOT NULL,
    active tinyint(1) DEFAULT true NOT NULL,
    created_by bigint,
    color varchar(20),
    uk_key_uk_qwt_tag_dict_scope_text varchar(32) GENERATED ALWAYS AS (IF((deleted = 0), MD5(CONCAT_WS('#', COALESCE(CAST(scope AS CHAR), '<n>'), COALESCE(CAST(text AS CHAR), '<n>'))), NULL)) STORED,
    PRIMARY KEY (id)
);

-- Name: qwt_tag_dict_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_tag_interactions; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_tag_interactions (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6),
    liked tinyint(1),
    score int,
    tag varchar(50) NOT NULL,
    user_id bigint NOT NULL,
    venue_id bigint NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_tag_interactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_users; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_users (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6),
    avatar_url varchar(500),
    nickname varchar(64),
    open_id varchar(64) NOT NULL,
    role varchar(20) NOT NULL,
    age int,
    gender varchar(16),
    city varchar(64),
    PRIMARY KEY (id)
);

-- Name: qwt_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venue_claims; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venue_claims (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) NOT NULL,
    venue_id bigint NOT NULL,
    user_id bigint NOT NULL,
    real_name varchar(50) NOT NULL,
    contact_phone varchar(20) NOT NULL,
    contact_wechat varchar(50),
    license_urls varchar(2000),
    note varchar(500),
    status varchar(20) DEFAULT 'PENDING' NOT NULL,
    handled_by bigint,
    handle_note varchar(500),
    handled_at datetime(6),
    uk_key_qwt_uk_claims_user_venue_pending varchar(32) GENERATED ALWAYS AS (IF(((status) = 'PENDING'), MD5(CONCAT_WS('#', COALESCE(CAST(user_id AS CHAR), '<n>'), COALESCE(CAST(venue_id AS CHAR), '<n>'))), NULL)) STORED,
    PRIMARY KEY (id)
);

-- Name: qwt_venue_claims_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venue_crowd_reports; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venue_crowd_reports (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) NOT NULL,
    venue_id bigint NOT NULL,
    user_id bigint NOT NULL,
    female_level int NOT NULL,
    male_level int,
    report_date date NOT NULL,
    modify_count int DEFAULT 0 NOT NULL,
    uk_key_qwt_idx_crowd_reports_user_day varchar(32) GENERATED ALWAYS AS (IF((deleted = 0), MD5(CONCAT_WS('#', COALESCE(CAST(venue_id AS CHAR), '<n>'), COALESCE(CAST(user_id AS CHAR), '<n>'), COALESCE(CAST(report_date AS CHAR), '<n>'))), NULL)) STORED,
    PRIMARY KEY (id)
);

-- Name: qwt_venue_crowd_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venue_feedbacks; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venue_feedbacks (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6),
    handled tinyint(1) NOT NULL,
    note varchar(500),
    type varchar(20) NOT NULL,
    user_id bigint,
    venue_id bigint NOT NULL,
    handled_at datetime(6),
    handled_by bigint,
    status varchar(20) DEFAULT 'PENDING' NOT NULL,
    handle_note varchar(500),
    field varchar(30),
    corrected_value varchar(500),
    uk_key_qwt_uk_feedbacks_user_venue_type_field_pending varchar(32) GENERATED ALWAYS AS (IF(((user_id IS NOT NULL) AND ((status) = 'PENDING') AND (field IS NOT NULL)), MD5(CONCAT_WS('#', COALESCE(CAST(user_id AS CHAR), '<n>'), COALESCE(CAST(venue_id AS CHAR), '<n>'), COALESCE(CAST(type AS CHAR), '<n>'), COALESCE(CAST(field AS CHAR), '<n>'))), NULL)) STORED,
    uk_key_qwt_uk_feedbacks_user_venue_type_pending varchar(32) GENERATED ALWAYS AS (IF(((user_id IS NOT NULL) AND ((status) = 'PENDING') AND (field IS NULL)), MD5(CONCAT_WS('#', COALESCE(CAST(user_id AS CHAR), '<n>'), COALESCE(CAST(venue_id AS CHAR), '<n>'), COALESCE(CAST(type AS CHAR), '<n>'))), NULL)) STORED,
    PRIMARY KEY (id)
);

-- Name: qwt_venue_feedbacks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venue_photos; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venue_photos (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) NOT NULL,
    venue_id bigint NOT NULL,
    url varchar(500) NOT NULL,
    status varchar(20) DEFAULT 'PENDING' NOT NULL,
    created_by bigint NOT NULL,
    sort_order int DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_venue_photos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venue_posts; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venue_posts (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6),
    content varchar(2000) NOT NULL,
    publisher_name varchar(64),
    publisher_type varchar(20) NOT NULL,
    title varchar(100) NOT NULL,
    venue_id bigint NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_venue_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venue_reactions; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venue_reactions (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6) NOT NULL,
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6) NOT NULL,
    reaction_code varchar(30) NOT NULL,
    user_id bigint NOT NULL,
    venue_id bigint NOT NULL,
    reaction_date date NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_venue_reactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venue_shares; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venue_shares (
    id bigint NOT NULL AUTO_INCREMENT,
    channel varchar(16),
    created_at datetime(6) NOT NULL,
    event_type varchar(16) NOT NULL,
    share_from bigint,
    user_id bigint,
    venue_id bigint NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_venue_shares_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venue_status_logs; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venue_status_logs (
    id bigint NOT NULL AUTO_INCREMENT,
    changed_by bigint,
    created_at datetime(6),
    from_status varchar(20),
    to_status varchar(20) NOT NULL,
    venue_id bigint NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_venue_status_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venue_status_reports; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venue_status_reports (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6),
    note varchar(500),
    occurred_at datetime(6),
    user_id bigint NOT NULL,
    venue_id bigint NOT NULL,
    type varchar(20) NOT NULL,
    expires_at datetime(6) NOT NULL,
    admin_action varchar(20),
    PRIMARY KEY (id)
);

-- Name: qwt_venue_status_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venue_status_watchers; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venue_status_watchers (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    updated_at datetime(6),
    deleted tinyint(1) NOT NULL,
    user_id bigint NOT NULL,
    venue_id bigint NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_venue_status_watchers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venue_views; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venue_views (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    user_id bigint,
    venue_id bigint NOT NULL,
    view_date date NOT NULL,
    source varchar(16) DEFAULT 'OTHER' NOT NULL,
    PRIMARY KEY (id)
);

-- Name: qwt_venue_views_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: qwt_venues; Type: TABLE; Schema: public; Owner: -
CREATE TABLE qwt_venues (
    id bigint NOT NULL AUTO_INCREMENT,
    created_at datetime(6),
    deleted tinyint(1) NOT NULL,
    updated_at datetime(6),
    address varchar(200),
    city varchar(50) NOT NULL,
    contact_phone varchar(20),
    description varchar(500),
    district varchar(50),
    image_url varchar(500),
    latitude double,
    longitude double,
    min_consumption decimal(10,2),
    name varchar(100) NOT NULL,
    price decimal(10,2),
    sort_weight int DEFAULT 0 NOT NULL,
    status varchar(20) DEFAULT 'OPEN' NOT NULL,
    tags varchar(500),
    wechat_qr varchar(500),
    photos varchar(5000),
    claimed_by bigint,
    partner_fees varchar(1000),
    tickets varchar(2000),
    business_hours varchar(1000),
    PRIMARY KEY (id)
);

-- Name: qwt_venues_id_seq; Type: SEQUENCE; Schema: public; Owner: -
-- (identity 已内联为 AUTO_INCREMENT)

-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
-- Name: system_settings; Type: TABLE; Schema: public; Owner: -
-- Name: user_api_configs; Type: TABLE; Schema: public; Owner: -
-- Name: user_memories; Type: TABLE; Schema: public; Owner: -
-- Name: user_preferences; Type: TABLE; Schema: public; Owner: -
-- Name: user_search_configs; Type: TABLE; Schema: public; Owner: -
-- Name: user_skill_files; Type: TABLE; Schema: public; Owner: -
-- Name: user_skills; Type: TABLE; Schema: public; Owner: -
-- Name: user_subscriptions; Type: TABLE; Schema: public; Owner: -
-- Name: users; Type: TABLE; Schema: public; Owner: -
-- Name: qwt_app_feedbacks qwt_app_feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_app_feedbacks 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_daily_checkins qwt_daily_checkins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_daily_checkins 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_ad_views qwt_dancer_ad_views_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancer_ad_views 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_cities qwt_dancer_cities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancer_cities 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_favorites qwt_dancer_favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancer_favorites 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_photos qwt_dancer_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancer_photos 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_recognition_tags qwt_dancer_recognition_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancer_recognition_tags 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_recognitions qwt_dancer_recognitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancer_recognitions 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_services qwt_dancer_services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancer_services 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_shares qwt_dancer_shares_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancer_shares 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_venues qwt_dancer_venues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancer_venues 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_verification_logs qwt_dancer_verification_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancer_verification_logs 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_views qwt_dancer_views_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancer_views 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancers qwt_dancers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_dancers 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_demand_records qwt_demand_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_demand_records 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_favorites qwt_favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_favorites 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_flyway_schema_history qwt_flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
-- Name: qwt_group_chats qwt_group_chats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_group_chats 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_users qwt_idx_users_open_id; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE qwt_users ADD CONSTRAINT qwt_idx_users_open_id UNIQUE (open_id);

-- Name: qwt_messages qwt_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_messages 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_ops_config qwt_ops_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_ops_config 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_points_accounts qwt_points_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_points_accounts 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_points_gates qwt_points_gates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_points_gates 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_points_transactions qwt_points_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_points_transactions 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_points_unlocks qwt_points_unlocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_points_unlocks 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_recruitment_contacts qwt_recruitment_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_recruitment_contacts 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_recruitments qwt_recruitments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_recruitments 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_tag_dict qwt_tag_dict_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_tag_dict 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_tag_interactions qwt_tag_interactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_tag_interactions 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_dancer_recognitions qwt_uk_dr_user_dancer_date; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE qwt_dancer_recognitions ADD CONSTRAINT qwt_uk_dr_user_dancer_date UNIQUE (user_id, dancer_id, recognition_date);

-- Name: qwt_dancer_recognition_tags qwt_uk_drt_recognition_tag; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE qwt_dancer_recognition_tags ADD CONSTRAINT qwt_uk_drt_recognition_tag UNIQUE (recognition_id, tag);

-- Name: qwt_dancer_venues qwt_uk_dv_dancer_venue_relation; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE qwt_dancer_venues ADD CONSTRAINT qwt_uk_dv_dancer_venue_relation UNIQUE (dancer_id, venue_id, relation);

-- Name: qwt_favorites qwt_uk_fav_user_venue; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE qwt_favorites ADD CONSTRAINT qwt_uk_fav_user_venue UNIQUE (user_id, venue_id);

-- Name: qwt_tag_interactions qwt_uk_ti_user_venue_tag; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE qwt_tag_interactions ADD CONSTRAINT qwt_uk_ti_user_venue_tag UNIQUE (user_id, venue_id, tag);

-- Name: qwt_venue_reactions qwt_uk_vr_user_venue_code_date; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE qwt_venue_reactions ADD CONSTRAINT qwt_uk_vr_user_venue_code_date UNIQUE (user_id, venue_id, reaction_code, reaction_date);

-- Name: qwt_users qwt_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_users 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venue_claims qwt_venue_claims_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venue_claims 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venue_crowd_reports qwt_venue_crowd_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venue_crowd_reports 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venue_feedbacks qwt_venue_feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venue_feedbacks 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venue_photos qwt_venue_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venue_photos 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venue_posts qwt_venue_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venue_posts 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venue_reactions qwt_venue_reactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venue_reactions 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venue_shares qwt_venue_shares_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venue_shares 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venue_status_logs qwt_venue_status_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venue_status_logs 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venue_status_reports qwt_venue_status_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venue_status_reports 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venue_status_watchers qwt_venue_status_watchers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venue_status_watchers 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venue_views qwt_venue_views_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venue_views 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: qwt_venues qwt_venues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
-- (PK qwt_venues 已内联为 CREATE TABLE PRIMARY KEY (id))

-- Name: idx_qwt_dancer_services_dancer; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_qwt_dancer_services_dancer ON qwt_dancer_services (dancer_id, active, sort_order);

-- Name: idx_qwt_demand_records_dancer; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_qwt_demand_records_dancer ON qwt_demand_records (dancer_id, created_at);

-- Name: idx_qwt_demand_records_feedback_pending; Type: INDEX; Schema: public; Owner: -
-- !! 部分索引（MySQL 不支持 WHERE 谓词）→ 全量索引（性能等价，占用略大）
CREATE INDEX idx_qwt_demand_records_feedback_pending ON qwt_demand_records (feedback_requested_at DESC);

-- Name: idx_qwt_demand_records_pending; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_qwt_demand_records_pending ON qwt_demand_records (dancer_id, status);

-- Name: idx_qwt_demand_records_rescue_origin; Type: INDEX; Schema: public; Owner: -
-- !! 部分唯一索引（MySQL 不支持 WHERE 谓词）→ 全量 UNIQUE：MySQL UNIQUE 允许多个 NULL，与「单列 IS NOT NULL」条件语义等价
CREATE UNIQUE INDEX idx_qwt_demand_records_rescue_origin ON qwt_demand_records (origin_demand_id);

-- Name: idx_qwt_demand_records_user; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_qwt_demand_records_user ON qwt_demand_records (user_id, created_at);

-- Name: idx_qwt_demand_records_user_dancer; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_qwt_demand_records_user_dancer ON qwt_demand_records (user_id, dancer_id);

-- Name: idx_qwt_tag_dict_scope; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_qwt_tag_dict_scope ON qwt_tag_dict (scope, active, sort_order);

-- Name: qwt_flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
-- Name: qwt_idx_ad_views_dancer; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_ad_views_dancer ON qwt_dancer_ad_views (dancer_id);

-- Name: qwt_idx_app_feedbacks_status_created; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_app_feedbacks_status_created ON qwt_app_feedbacks (status, created_at);

-- Name: qwt_idx_app_feedbacks_user; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_app_feedbacks_user ON qwt_app_feedbacks (user_id);

-- Name: qwt_idx_checkins_user; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_checkins_user ON qwt_daily_checkins (user_id);

-- Name: qwt_idx_city; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_city ON qwt_venues (city);

-- Name: qwt_idx_claimed_by; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_claimed_by ON qwt_venues (claimed_by);

-- Name: qwt_idx_claims_status; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_claims_status ON qwt_venue_claims (status);

-- Name: qwt_idx_claims_user_id; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_claims_user_id ON qwt_venue_claims (user_id);

-- Name: qwt_idx_claims_venue_id; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_claims_venue_id ON qwt_venue_claims (venue_id);

-- Name: qwt_idx_crowd_reports_user_day; Type: INDEX; Schema: public; Owner: -
-- !! 部分唯一索引 → 生成列 uk_key_qwt_idx_crowd_reports_user_day + UNIQUE（见 CREATE TABLE 生成列）
CREATE UNIQUE INDEX qwt_idx_crowd_reports_user_day ON qwt_venue_crowd_reports (uk_key_qwt_idx_crowd_reports_user_day);

-- Name: qwt_idx_crowd_reports_venue_created; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_crowd_reports_venue_created ON qwt_venue_crowd_reports (venue_id, created_at);

-- Name: qwt_idx_dancer_cities_city; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancer_cities_city ON qwt_dancer_cities (city);

-- Name: qwt_idx_dancer_cities_dancer; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancer_cities_dancer ON qwt_dancer_cities (dancer_id);

-- Name: qwt_idx_dancer_fav_dancer; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancer_fav_dancer ON qwt_dancer_favorites (dancer_id);

-- Name: qwt_idx_dancer_fav_user; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancer_fav_user ON qwt_dancer_favorites (user_id);

-- Name: qwt_idx_dancer_shares_dancer_time; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancer_shares_dancer_time ON qwt_dancer_shares (dancer_id, created_at);

-- Name: qwt_idx_dancer_shares_from; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancer_shares_from ON qwt_dancer_shares (share_from);

-- Name: qwt_idx_dancer_shares_user; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancer_shares_user ON qwt_dancer_shares (user_id);

-- Name: qwt_idx_dancer_views_dancer_date; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancer_views_dancer_date ON qwt_dancer_views (dancer_id, view_date);

-- Name: qwt_idx_dancer_views_source; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancer_views_source ON qwt_dancer_views (dancer_id, view_date, source);

-- Name: qwt_idx_dancer_views_user; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancer_views_user ON qwt_dancer_views (user_id);

-- Name: qwt_idx_dancers_city; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancers_city ON qwt_dancers (city);

-- Name: qwt_idx_dancers_created_by; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancers_created_by ON qwt_dancers (created_by);

-- Name: qwt_idx_dancers_status; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dancers_status ON qwt_dancers (status);

-- Name: qwt_idx_district; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_district ON qwt_venues (district);

-- Name: qwt_idx_dp_dancer; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dp_dancer ON qwt_dancer_photos (dancer_id);

-- Name: qwt_idx_dp_dancer_status; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dp_dancer_status ON qwt_dancer_photos (dancer_id, status);

-- Name: qwt_idx_dp_status_created; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dp_status_created ON qwt_dancer_photos (status, created_at);

-- Name: qwt_idx_dr_dancer_created; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dr_dancer_created ON qwt_dancer_recognitions (dancer_id, created_at);

-- Name: qwt_idx_dr_dancer_date; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dr_dancer_date ON qwt_dancer_recognitions (dancer_id, recognition_date);

-- Name: qwt_idx_dr_user; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dr_user ON qwt_dancer_recognitions (user_id);

-- Name: qwt_idx_drt_dancer_created; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_drt_dancer_created ON qwt_dancer_recognition_tags (dancer_id, created_at);

-- Name: qwt_idx_drt_dancer_tag; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_drt_dancer_tag ON qwt_dancer_recognition_tags (dancer_id, tag);

-- Name: qwt_idx_drt_recognition; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_drt_recognition ON qwt_dancer_recognition_tags (recognition_id);

-- Name: qwt_idx_dv_dancer; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dv_dancer ON qwt_dancer_venues (dancer_id);

-- Name: qwt_idx_dv_venue; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_dv_venue ON qwt_dancer_venues (venue_id);

-- Name: qwt_idx_fav_user_id; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_fav_user_id ON qwt_favorites (user_id);

-- Name: qwt_idx_fav_venue_deleted; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_fav_venue_deleted ON qwt_favorites (venue_id, deleted);

-- Name: qwt_idx_fav_venue_id; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_fav_venue_id ON qwt_favorites (venue_id);

-- Name: qwt_idx_feedbacks_handled; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_feedbacks_handled ON qwt_venue_feedbacks (handled, created_at);

-- Name: qwt_idx_feedbacks_status_created; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_feedbacks_status_created ON qwt_venue_feedbacks (status, created_at);

-- Name: qwt_idx_feedbacks_user_id; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_feedbacks_user_id ON qwt_venue_feedbacks (user_id);

-- Name: qwt_idx_feedbacks_venue_id; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_feedbacks_venue_id ON qwt_venue_feedbacks (venue_id);

-- Name: qwt_idx_group_chats_city_deleted; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_group_chats_city_deleted ON qwt_group_chats (city, deleted);

-- Name: qwt_idx_group_chats_scope_deleted; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_group_chats_scope_deleted ON qwt_group_chats (scope, deleted);

-- Name: qwt_idx_messages_user_created; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_messages_user_created ON qwt_messages (user_id, created_at);

-- Name: qwt_idx_messages_user_read; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_messages_user_read ON qwt_messages (user_id, read_at);

-- Name: qwt_idx_points_gates_target_type; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_points_gates_target_type ON qwt_points_gates (target_type, target_id, deleted);

-- Name: qwt_idx_points_unlocks_target; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_points_unlocks_target ON qwt_points_unlocks (target_type, target_id);

-- Name: qwt_idx_posts_created_at; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_posts_created_at ON qwt_venue_posts (created_at);

-- Name: qwt_idx_posts_venue_deleted; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_posts_venue_deleted ON qwt_venue_posts (venue_id, deleted);

-- Name: qwt_idx_posts_venue_id; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_posts_venue_id ON qwt_venue_posts (venue_id);

-- Name: qwt_idx_pts_tx_target; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_pts_tx_target ON qwt_points_transactions (target_type, target_id, created_at);

-- Name: qwt_idx_pts_tx_target_gift_code; Type: INDEX; Schema: public; Owner: -
-- !! 部分索引（MySQL 不支持 WHERE 谓词）→ 全量索引（性能等价，占用略大）
CREATE INDEX qwt_idx_pts_tx_target_gift_code ON qwt_points_transactions (target_type, target_id, gift_code);

-- Name: qwt_idx_pts_tx_user_created; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_pts_tx_user_created ON qwt_points_transactions (user_id, created_at);

-- Name: qwt_idx_recruitment_contacts_unique; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX qwt_idx_recruitment_contacts_unique ON qwt_recruitment_contacts (recruitment_id, user_id);

-- Name: qwt_idx_recruitments_status_expires; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_recruitments_status_expires ON qwt_recruitments (status, expires_at);

-- Name: qwt_idx_recruitments_venue; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_recruitments_venue ON qwt_recruitments (venue_id);

-- Name: qwt_idx_sort_weight; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_sort_weight ON qwt_venues (sort_weight);

-- Name: qwt_idx_status; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_status ON qwt_venues (status);

-- Name: qwt_idx_status_logs_venue_time; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_status_logs_venue_time ON qwt_venue_status_logs (venue_id, created_at);

-- Name: qwt_idx_status_reports_user; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_status_reports_user ON qwt_venue_status_reports (user_id);

-- Name: qwt_idx_status_reports_venue_created; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_status_reports_venue_created ON qwt_venue_status_reports (venue_id, created_at);

-- Name: qwt_idx_status_reports_venue_expires; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_status_reports_venue_expires ON qwt_venue_status_reports (venue_id, expires_at);

-- Name: qwt_idx_ti_user_id; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_ti_user_id ON qwt_tag_interactions (user_id);

-- Name: qwt_idx_ti_venue_tag; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_ti_venue_tag ON qwt_tag_interactions (venue_id, tag);

-- Name: qwt_idx_ti_venue_tag_updated; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_ti_venue_tag_updated ON qwt_tag_interactions (venue_id, tag, updated_at);

-- Name: qwt_idx_venue_shares_from; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_venue_shares_from ON qwt_venue_shares (share_from);

-- Name: qwt_idx_venue_shares_user; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_venue_shares_user ON qwt_venue_shares (user_id);

-- Name: qwt_idx_venue_shares_venue_time; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_venue_shares_venue_time ON qwt_venue_shares (venue_id, created_at);

-- Name: qwt_idx_venue_status_watchers_user_venue; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX qwt_idx_venue_status_watchers_user_venue ON qwt_venue_status_watchers (user_id, venue_id);

-- Name: qwt_idx_venue_status_watchers_venue; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_venue_status_watchers_venue ON qwt_venue_status_watchers (venue_id);

-- Name: qwt_idx_venue_views_source; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_venue_views_source ON qwt_venue_views (venue_id, view_date, source);

-- Name: qwt_idx_venue_views_user; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_venue_views_user ON qwt_venue_views (user_id);

-- Name: qwt_idx_venue_views_venue_date; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_venue_views_venue_date ON qwt_venue_views (venue_id, view_date);

-- Name: qwt_idx_verification_logs_dancer; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_verification_logs_dancer ON qwt_dancer_verification_logs (dancer_id);

-- Name: qwt_idx_vp_status_created; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_vp_status_created ON qwt_venue_photos (status, created_at);

-- Name: qwt_idx_vp_venue; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_vp_venue ON qwt_venue_photos (venue_id);

-- Name: qwt_idx_vp_venue_status; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_vp_venue_status ON qwt_venue_photos (venue_id, status);

-- Name: qwt_idx_vr_user_id; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_vr_user_id ON qwt_venue_reactions (user_id);

-- Name: qwt_idx_vr_venue_code; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_vr_venue_code ON qwt_venue_reactions (venue_id, reaction_code);

-- Name: qwt_idx_vr_venue_code_created; Type: INDEX; Schema: public; Owner: -
CREATE INDEX qwt_idx_vr_venue_code_created ON qwt_venue_reactions (venue_id, reaction_code, created_at);

-- Name: qwt_uk_ad_views_user_dancer_date; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX qwt_uk_ad_views_user_dancer_date ON qwt_dancer_ad_views (user_id, dancer_id, view_date);

-- Name: qwt_uk_checkins_user_date; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX qwt_uk_checkins_user_date ON qwt_daily_checkins (user_id, checkin_date);

-- Name: qwt_uk_claims_user_venue_pending; Type: INDEX; Schema: public; Owner: -
-- !! 部分唯一索引 → 生成列 uk_key_qwt_uk_claims_user_venue_pending + UNIQUE（见 CREATE TABLE 生成列）
CREATE UNIQUE INDEX qwt_uk_claims_user_venue_pending ON qwt_venue_claims (uk_key_qwt_uk_claims_user_venue_pending);

-- Name: qwt_uk_dancer_fav_user_dancer; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX qwt_uk_dancer_fav_user_dancer ON qwt_dancer_favorites (user_id, dancer_id);

-- Name: qwt_uk_feedbacks_user_venue_type_field_pending; Type: INDEX; Schema: public; Owner: -
-- !! 部分唯一索引 → 生成列 uk_key_qwt_uk_feedbacks_user_venue_type_field_pending + UNIQUE（见 CREATE TABLE 生成列）
CREATE UNIQUE INDEX qwt_uk_feedbacks_user_venue_type_field_pending ON qwt_venue_feedbacks (uk_key_qwt_uk_feedbacks_user_venue_type_field_pending);

-- Name: qwt_uk_feedbacks_user_venue_type_pending; Type: INDEX; Schema: public; Owner: -
-- !! 部分唯一索引 → 生成列 uk_key_qwt_uk_feedbacks_user_venue_type_pending + UNIQUE（见 CREATE TABLE 生成列）
CREATE UNIQUE INDEX qwt_uk_feedbacks_user_venue_type_pending ON qwt_venue_feedbacks (uk_key_qwt_uk_feedbacks_user_venue_type_pending);

-- Name: qwt_uk_ops_config_key; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX qwt_uk_ops_config_key ON qwt_ops_config (`key`);

-- Name: qwt_uk_points_accounts_user; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX qwt_uk_points_accounts_user ON qwt_points_accounts (user_id);

-- Name: qwt_uk_points_gates_target; Type: INDEX; Schema: public; Owner: -
-- !! 部分唯一索引 → 生成列 uk_key_qwt_uk_points_gates_target + UNIQUE（见 CREATE TABLE 生成列）
CREATE UNIQUE INDEX qwt_uk_points_gates_target ON qwt_points_gates (uk_key_qwt_uk_points_gates_target);

-- Name: qwt_uk_points_unlocks_user_target; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX qwt_uk_points_unlocks_user_target ON qwt_points_unlocks (user_id, target_type, target_id);

-- Name: qwt_uk_pts_tx_earn_dedup; Type: INDEX; Schema: public; Owner: -
-- !! 部分唯一索引 → 生成列 uk_key_qwt_uk_pts_tx_earn_dedup + UNIQUE（见 CREATE TABLE 生成列）
CREATE UNIQUE INDEX qwt_uk_pts_tx_earn_dedup ON qwt_points_transactions (uk_key_qwt_uk_pts_tx_earn_dedup);

-- Name: qwt_uq_dancer_views_dedup; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX qwt_uq_dancer_views_dedup ON qwt_dancer_views (dancer_id, user_id, view_date, source);

-- Name: qwt_uq_venue_views_dedup; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX qwt_uq_venue_views_dedup ON qwt_venue_views (venue_id, user_id, view_date, source);

-- Name: uk_qwt_dancer_services_dancer_label; Type: INDEX; Schema: public; Owner: -
-- !! 部分唯一索引 → 生成列 uk_key_uk_qwt_dancer_services_dancer_label + UNIQUE（见 CREATE TABLE 生成列）
CREATE UNIQUE INDEX uk_qwt_dancer_services_dancer_label ON qwt_dancer_services (uk_key_uk_qwt_dancer_services_dancer_label);

-- Name: uk_qwt_tag_dict_scope_text; Type: INDEX; Schema: public; Owner: -
-- !! 部分唯一索引 → 生成列 uk_key_uk_qwt_tag_dict_scope_text + UNIQUE（见 CREATE TABLE 生成列）
CREATE UNIQUE INDEX uk_qwt_tag_dict_scope_text ON qwt_tag_dict (uk_key_uk_qwt_tag_dict_scope_text);

