#!/usr/bin/env python3
"""PG schema (pg_dump) → MySQL DDL 转换器（quwuting 专用，v2 支持部分索引）。

规则：
- 只处理 public.qwt_* 对象，跳过 qwt_flyway_schema_history（Flyway 自建）
- bigint GENERATED BY DEFAULT AS IDENTITY → bigint AUTO_INCREMENT（内联 id 列）
- boolean → tinyint(1)；timestamp → datetime(6)；time → time；double precision → double
- numeric → decimal；character varying → varchar；DEFAULT 'x'::xxx → DEFAULT 'x'
- ADD CONSTRAINT ... PRIMARY KEY (id) → ADD PRIMARY KEY (id)
- ADD CONSTRAINT name UNIQUE → 保留（MySQL 8 支持）
- 普通索引 USING btree (a,b) → (a,b)；DESC 排序保留（MySQL 8 支持）
- 部分索引 WHERE (cond)：
  * 非唯一 → 转全量索引（性能等价，注释标注）
  * 唯一且条件为「单列 IS NOT NULL」→ 转全量 UNIQUE（MySQL UNIQUE 允许多个 NULL，语义等价）
  * 其余唯一部分索引 → 生成列方案：uk_key_<idx> = IF(cond, MD5(CONCAT_WS('#', cols...)), NULL) STORED
    + UNIQUE KEY 建在生成列上（精确复刻 PG 部分唯一索引语义：条件不满足行生成列=NULL 不受约束）
- qwt_city_key(text) → MySQL DETERMINISTIC 函数（LEFT(city,-1) → LEFT(city,LENGTH(city)-1)）
"""
import re

SRC = '/tmp/qwt_pg_schema.sql'
DST = '/tmp/qwt_mysql_baseline.sql'


def strip_casts(x: str) -> str:
    x = x.replace('::character varying', '')
    x = x.replace('::text', '')
    x = x.replace('::timestamp without time zone', '')
    return re.sub(r"::\w+", "", x)


def conv_type(t: str) -> str:
    t = t.strip()
    t = re.sub(r'timestamp\(\d+\) without time zone', 'datetime(6)', t)
    t = re.sub(r'timestamp without time zone', 'datetime(6)', t)
    t = re.sub(r'time\(\d+\) without time zone', 'time(6)', t)
    t = re.sub(r'time without time zone', 'time', t)
    t = re.sub(r'character varying\((\d+)\)', r'varchar(\1)', t)
    t = re.sub(r'\bdouble precision\b', 'double', t)
    t = re.sub(r'\bnumeric\((\d+),\s*(\d+)\)', r'decimal(\1,\2)', t)
    t = re.sub(r'\bboolean\b', 'tinyint(1)', t)
    t = re.sub(r'\binteger\b', 'int', t)
    t = re.sub(r'\bjsonb\b', 'json', t)
    t = re.sub(r'\breal\b', 'float', t)
    return t


def conv_default(d: str) -> str:
    d = d.replace('::character varying', '')
    d = d.replace('::timestamp without time zone', '')
    d = d.replace('::time without time zone', '')
    d = re.sub(r"::\w+", "", d)
    return d.strip()


def pg_cond_to_mysql(cond: str) -> str:
    """PG 布尔条件 → MySQL 布尔条件（去 cast、false→0）。"""
    c = strip_casts(cond).strip()
    c = re.sub(r"\bfalse\b", "0", c)
    c = re.sub(r"\btrue\b", "1", c)
    # 去多余括号：((a) = (b)) → (a = b)
    return c


def extract_cols(cols: str):
    """索引列清单 'a, b DESC' → [('a',''), ('b','DESC')]；去 pg 引号与 cast。"""
    result = []
    for part in cols.split(','):
        part = strip_casts(part.strip())
        part = re.sub(r'^\(|\)$', '', part.strip())
        m = re.match(r'(.+?)(\s+(ASC|DESC))?$', part)
        name = m.group(1).strip()
        direction = m.group(3) or ''
        result.append((name, direction))
    return result


# MySQL 8.0 保留字（列名需反引号包裹）
RESERVED = set("""ACCESSIBLE ADD ALL ALTER ANALYZE AND AS ASC ASENSITIVE BEFORE BETWEEN BIGINT BINARY BLOB BOTH BY CALL CASCADE CASE CHANGE CHAR CHARACTER CHECK COLLATE COLUMN CONDITION CONNECTION CONSTRAINT CONTINUE CONVERT CREATE CROSS CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR DATABASE DATABASES DAY_HOUR DAY_MICROSECOND DAY_MINUTE DAY_SECOND DEC DECIMAL DECLARE DEFAULT DELAYED DELETE DESC DESCRIBE DETERMINISTIC DISTINCT DISTINCTROW DIV DOUBLE DROP DUAL EACH ELSE ELSEIF ENCLOSED ESCAPED EXISTS EXIT EXPLAIN FALSE FETCH FLOAT FLOAT4 FLOAT8 FOR FORCE FOREIGN FROM FULLTEXT GENERATED GET GRANT GROUP GROUPING GROUPS HAVING HIGH_PRIORITY HOUR_MICROSECOND HOUR_MINUTE HOUR_SECOND IF IGNORE IN INDEX INFILE INNER INOUT INSENSITIVE INSERT INT INT1 INT2 INT3 INT4 INT8 INTEGER INTERVAL INTO IO_AFTER_GTIDS IO_BEFORE_GTIDS IS ITERATE JOIN JSON KEY KEYS KILL LATERAL LEADING LEAVE LEFT LIKE LIMIT LINEAR LINES LOAD LOCALTIME LOCALTIMESTAMP LOCK LONG LONGBLOB LONGTEXT LOOP LOW_PRIORITY MASTER_BIND MASTER_SSL_VERIFY_SERVER_CERT MATCH MAXVALUE MEDIUMBLOB MEDIUMINT MEDIUMTEXT MIDDLEINT MINUTE_MICROSECOND MINUTE_SECOND MOD MODIFIES NATURAL NOT NO_WRITE_TO_BINLOG NULL NUMERIC ON OPTIMIZE OPTIMIZER_COSTS OPTION OPTIONALLY OR ORDER OUT OUTER OUTFILE PARTITION PRECISION PRIMARY PROCEDURE PURGE RANGE RANK READ READS READ_WRITE REAL RECURSIVE REFERENCES REGEXP RELEASE RENAME REPEAT REPLACE REQUIRE RESIGNAL RESTRICT RETURN REVOKE RIGHT RLIKE ROW ROWS SCHEMA SCHEMAS SECOND_MICROSECOND SELECT SENSITIVE SEPARATOR SET SHOW SIGNAL SMALLINT SPATIAL SPECIFIC SQL SQLEXCEPTION SQLSTATE SQLWARNING SQL_BIG_RESULT SQL_CALC_FOUND_ROWS SQL_SMALL_RESULT SSL STARTING STORED STRAIGHT_JOIN SYSTEM TABLE TERMINATED THEN TINYBLOB TINYINT TINYTEXT TO TRAILING TRIGGER TRUE UNDO UNION UNIQUE UNLOCK UNSIGNED UPDATE USAGE USE USING UTC_DATE UTC_TIME UTC_TIMESTAMP VALUES VARBINARY VARCHAR VARCHARACTER VARYING VIRTUAL WHEN WHERE WHILE WINDOW WITH WRITE XOR YEAR_MONTH ZEROFILL""".split())


def q(name: str) -> str:
    """保留字列名加反引号。"""
    return f'`{name}`' if name.upper() in RESERVED else name


def main():
    src = open(SRC).read()
    stmts = re.split(r';\s*\n', src)
    out = []
    seen_index_names = {}
    partial_unique = []  # (tbl, idx, cols_str, cond) 待生成列处理

    # 第一遍：收集部分唯一索引（需在表定义追加生成列；「单列 IS NOT NULL」简单形态除外——
    # 该类转全量 UNIQUE 即可（MySQL UNIQUE 允许多个 NULL，语义等价））
    for raw in stmts:
        body = '\n'.join(l for l in raw.split('\n') if not l.strip().startswith('--')).strip()
        if not body:
            continue
        m = re.match(r'CREATE (UNIQUE )?INDEX (\w+) ON public\.(qwt_\w+) USING btree \((.*?)\)\s+WHERE\s+(.+)$', body, re.S)
        if m and m.group(1):
            cols_str, cond = m.group(4), m.group(5)
            cond_s = strip_casts(cond).strip()
            is_simple = bool(re.fullmatch(r'\(?\w+ IS NOT NULL\)?', cond_s)) and len(extract_cols(cols_str)) == 1
            if not is_simple:
                partial_unique.append((m.group(3), m.group(2), cols_str, cond))

    partial_map = {}  # tbl -> [(idx, cols, cond)]
    for tbl, idx, cols, cond in partial_unique:
        partial_map.setdefault(tbl, []).append((idx, cols, cond))

    # 第二遍：输出
    for raw in stmts:
        lines = raw.split('\n')
        comment_lines = [ln for ln in lines if ln.strip().startswith('--')]
        body = '\n'.join(ln for ln in lines if not ln.strip().startswith('--')).strip()
        if not body:
            continue
        name_lines = [ln.strip() for ln in comment_lines if 'Name:' in ln]
        if name_lines:
            out.append('-- ' + name_lines[0].lstrip('- ').strip())
        s = body

        # ---- CREATE TABLE ----
        m = re.match(r'CREATE TABLE public\.(qwt_\w+) \(', s, re.S)
        if m:
            tbl = m.group(1)
            if tbl == 'qwt_flyway_schema_history':
                out.append(f'-- (skipped: {tbl} — Flyway 自建表)')
                out.append('')
                continue
            body_in = s[s.index('(') + 1:s.rindex(')')]
            cols = []
            for cl in body_in.split('\n'):
                cl = cl.strip().rstrip(',')
                if not cl:
                    continue
                mm = re.match(r'(\w+)\s+(.+)$', cl)
                if not mm:
                    raise SystemExit(f'[table {tbl}] 无法解析列: {cl!r}')
                name, rest = mm.group(1), mm.group(2)
                dm = re.search(r'\s+DEFAULT\s+(.+)$', rest)
                default = ''
                if dm:
                    default = dm.group(1).strip()
                    rest = rest[:dm.start()].rstrip()
                nn = ' NOT NULL' if re.search(r'\bNOT NULL\b', rest) else ''
                rest = re.sub(r'\bNOT NULL\b', '', rest).strip()
                typ = conv_type(rest)
                if default:
                    d = conv_default(default)
                    if d and 'nextval' not in d:
                        typ += f' DEFAULT {d}'
                if nn:
                    typ += ' NOT NULL'
                if name == 'id':
                    typ = typ.replace(' NOT NULL', ' NOT NULL AUTO_INCREMENT')
                    if 'AUTO_INCREMENT' not in typ:
                        typ += ' AUTO_INCREMENT'
                cols.append((name, typ))
            lines_out = [f'CREATE TABLE {tbl} (']
            for name, typ in cols:
                lines_out.append(f'    {q(name)} {typ},')
            # 部分唯一索引 → 追加生成列
            for idx, cols_str, cond in partial_map.get(tbl, []):
                col_parts = extract_cols(cols_str)
                inner = ', '.join(f"COALESCE(CAST({q(n)} AS CHAR), '<n>')" for n, _ in col_parts)
                cond_m = pg_cond_to_mysql(cond)
                lines_out.append(
                    f'    uk_key_{idx} varchar(32) GENERATED ALWAYS AS '
                    f'(IF({cond_m}, MD5(CONCAT_WS(\'#\', {inner})), NULL)) STORED,')
            # 主键内联（MySQL: AUTO_INCREMENT 列必须为 key；本项目全表主键 = 单列 id）
            lines_out.append('    PRIMARY KEY (id)')
            lines_out.append(');')
            out.extend(lines_out)
            out.append('')
            continue

        # ---- ALTER TABLE ... ADD GENERATED IDENTITY（已内联）----
        if re.search(r'ADD GENERATED BY DEFAULT AS IDENTITY', s, re.S):
            out.append('-- (identity 已内联为 AUTO_INCREMENT)')
            out.append('')
            continue

        # ---- ALTER TABLE ... ADD CONSTRAINT PRIMARY KEY（已内联到 CREATE TABLE，跳过）----
        m = re.match(r'ALTER TABLE ONLY public\.(qwt_\w+)\s+ADD CONSTRAINT \w+ PRIMARY KEY \((.*?)\)$', s, re.S)
        if m:
            if m.group(1) == 'qwt_flyway_schema_history':
                continue
            out.append(f'-- (PK {m.group(1)} 已内联为 CREATE TABLE PRIMARY KEY (id))')
            out.append('')
            continue

        # ---- ALTER TABLE ... ADD CONSTRAINT ... UNIQUE ----
        m = re.match(r'ALTER TABLE ONLY public\.(qwt_\w+)\s+ADD CONSTRAINT (\w+) UNIQUE \((.*?)\)$', s, re.S)
        if m:
            out.append(f'ALTER TABLE {m.group(1)} ADD CONSTRAINT {m.group(2)} UNIQUE ({m.group(3)});')
            out.append('')
            continue

        # ---- CREATE [UNIQUE] INDEX（含部分索引）----
        m = re.match(r'CREATE (UNIQUE )?INDEX (\w+) ON public\.(qwt_\w+) USING btree \((.*?)\)(\s+WHERE\s+(.+))?$', s, re.S)
        if m:
            uniq, idx, tbl, cols, _, where_cond = m.group(1), m.group(2), m.group(3), m.group(4), m.group(5), m.group(6)
            if tbl == 'qwt_flyway_schema_history':
                continue
            if idx in seen_index_names and seen_index_names[idx] != tbl:
                out.append(f'-- !! 索引名冲突（MySQL 表级唯一）: {idx} 改名 {idx}_b')
                idx = idx + '_b'
            seen_index_names[idx] = tbl
            col_parts = extract_cols(cols)
            cols_sql = ', '.join(f'{q(n)} {d}'.strip() for n, d in col_parts)
            if where_cond:
                cond = pg_cond_to_mysql(where_cond)
                if uniq:
                    # 唯一部分索引
                    is_simple_null = re.fullmatch(r'\(?\w+ IS NOT NULL\)?', cond)
                    if is_simple_null:
                        out.append(f'-- !! 部分唯一索引（MySQL 不支持 WHERE 谓词）→ 全量 UNIQUE：'
                                   f'MySQL UNIQUE 允许多个 NULL，与「单列 IS NOT NULL」条件语义等价')
                        out.append(f'CREATE UNIQUE INDEX {idx} ON {tbl} ({cols_sql});')
                    else:
                        out.append(f'-- !! 部分唯一索引 → 生成列 uk_key_{idx} + UNIQUE（见 CREATE TABLE 生成列）')
                        out.append(f'CREATE UNIQUE INDEX {idx} ON {tbl} (uk_key_{idx});')
                else:
                    out.append(f'-- !! 部分索引（MySQL 不支持 WHERE 谓词）→ 全量索引（性能等价，占用略大）')
                    out.append(f'CREATE INDEX {idx} ON {tbl} ({cols_sql});')
            else:
                out.append(f'CREATE {uniq or ""}INDEX {idx} ON {tbl} ({cols_sql});')
            out.append('')
            continue

        # ---- CREATE FUNCTION qwt_city_key ----
        if 'CREATE FUNCTION public.qwt_city_key' in s:
            out.append('-- qwt_city_key: 城市名规范化（去「市」后缀），供 native SQL 使用（DancerRepository）')
            out.append("CREATE FUNCTION qwt_city_key(city TEXT) RETURNS TEXT DETERMINISTIC")
            out.append("RETURN CASE WHEN RIGHT(city, 1) = '市' THEN LEFT(city, LENGTH(city) - 1) ELSE city END;")
            out.append('')
            continue

        # ---- 跳过项 ----
        if (s.startswith('SET ') or s.startswith('SELECT pg_catalog')
                or s.startswith('\\restrict') or s.startswith('\\unrestrict')
                or s.startswith('CREATE SCHEMA')
                or 'OWNER TO' in s or s.startswith('GRANT') or s.startswith('REVOKE')
                or s.startswith('COMMENT ON')
                or re.match(r'ALTER TABLE ONLY public\.(?!qwt_)', s)
                or re.match(r'CREATE TABLE public\.(?!qwt_)', s)
                or re.match(r'CREATE (UNIQUE )?INDEX \w+ ON public\.(?!qwt_)', s)
                or s.startswith('ALTER SEQUENCE') or s.startswith('CREATE SEQUENCE')):
            continue
        out.append(f'-- ??? 未识别语句（人工审查）:')
        for ln in s.split('\n'):
            out.append('--   ' + ln)
        out.append('')

    open(DST, 'w').write('\n'.join(out) + '\n')
    print(f'written: {DST} ({len(out)} lines)')


if __name__ == '__main__':
    main()
