-- ============================================================================
-- V12: 门店认领申请（2026-08-11，需求「认领舞厅」）
--
-- 背景：门店数据由平台录入，普通用户无权直接编辑。认领 = 门店工作人员
-- （老板/经理/店员）申请成为该店管理方，平台管理员审核通过后置
-- qwt_venues.claimed_by = 申请人 userId——此后 canManage 判定（认领人或
-- 平台管理员）自动生效，用户获得门店管理权（编辑信息/发布动态等），
-- 无需改动任何权限体系。
--
-- 本表是认领申请工单：一张申请单对应「一个用户认领一个门店」，含申请材料
-- （真实姓名/手机号/微信号/营业执照/补充说明）与审核结果（处理人/备注/时间）。
-- 与 venuefeedback（信息纠错）语义区分：反馈是"数据有错"的异步上报；
-- 认领是"身份归属"的权限申请，走独立状态机。
--
-- 状态机（ClaimStatus）：
--   PENDING（待审核）→ APPROVED（已通过：置 venue.claimed_by）/ REJECTED（已拒绝）
--   PENDING → WITHDRAWN（申请人主动撤回）
--   APPROVED/REJECTED/WITHDRAWN 均为终态；REJECTED 后用户可再次提交新申请。
--
-- 唯一约束设计（防重复申请，复用 V2/V8 部分唯一索引先例）：
--   同一用户对同一门店最多一条 PENDING——连点/重复提交被库内幂等，
--   冲突由应用层 catch DataIntegrityViolationException（23505）按
--   (user_id, venue_id) 回查已有 PENDING 记录幂等返回。
--   终态（APPROVED/REJECTED/WITHDRAWN）不受索引约束，历史记录保留。
--
-- 幂等：Flyway 按版本只执行一次；IF NOT EXISTS 均为防御性写法。
-- ============================================================================

CREATE TABLE qwt_venue_claims (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp(6),
    updated_at     timestamp(6),
    deleted        boolean NOT NULL,
    -- 目标门店（qwt_venues.id）
    venue_id       bigint NOT NULL,
    -- 申请人（qwt_users.id），认领必须登录，恒非空
    user_id        bigint NOT NULL,
    -- 申请材料：真实姓名（必填）/ 手机号（必填）/ 微信号（选填）
    real_name      varchar(50)  NOT NULL,
    contact_phone  varchar(20)  NOT NULL,
    contact_wechat varchar(50),
    -- 营业执照照片 URL 列表（JSON 数组字符串，最多 3 张，与 photos 同模式；选填）
    license_urls   varchar(2000),
    -- 补充说明（选填，最多 200 字）
    note           varchar(500),
    -- 审核状态（唯一事实源 = 本列；默认值声明见 entity @ColumnDefault）
    status         varchar(20)  NOT NULL DEFAULT 'PENDING',
    -- 审核人用户 ID（管理员处理时写入，未处理为 null）
    handled_by     bigint,
    -- 审核结果说明（如拒绝原因 / 通过说明，随「我的认领」回传申请人）
    handle_note    varchar(500),
    -- 审核时间
    handled_at     timestamp(6)
);

-- 查询索引：管理端按门店/状态过滤、用户侧按 userId 查我的认领
CREATE INDEX IF NOT EXISTS qwt_idx_claims_venue_id   ON qwt_venue_claims (venue_id);
CREATE INDEX IF NOT EXISTS qwt_idx_claims_user_id    ON qwt_venue_claims (user_id);
CREATE INDEX IF NOT EXISTS qwt_idx_claims_status     ON qwt_venue_claims (status);

-- 防重复申请：同一 (user_id, venue_id) 最多一条 PENDING
CREATE UNIQUE INDEX IF NOT EXISTS qwt_uk_claims_user_venue_pending
    ON qwt_venue_claims (user_id, venue_id)
    WHERE status = 'PENDING';
