-- ── V14：关注门店营业状态（qwt_venue_status_watchers，2026-08-12 新增） ──────
-- 需求（用户）：门店详情页可开启「营业状态变化通知」——该店营业状态每次变更时，
-- 关注者收到站内信（VENUE_STATUS_CHANGED）+ 首页提醒卡片（未读即提醒），点击深链
-- 门店详情页。决策：不依赖微信订阅消息（一次性订阅体验受限），纯应用内站内信通知
-- （见 AGENTS.md「关注门店营业状态通知」）。
--
-- 设计要点：
-- 1. 与收藏表（qwt_favorites）解耦——关注=只盯营业状态变化，不收藏也能开通知
--    （如"这家暂停营业了，等它恢复"），语义独立；
-- 2. 唯一约束 (user_id, venue_id)：同一用户对同一门店只关注一次，重复 PUT 幂等；
-- 3. 索引 (venue_id)：状态变更时按门店查关注者（通知发送查询路径）；
-- 4. 软删列（deleted）沿用 BaseEntity 约定；取消关注 = 物理删除（无审计价值，
--    与 reaction 取消同语义）；
-- 5. 通知 = 复用 qwt_messages 站内信（MessageType.VENUE_STATUS_CHANGED），
--    不新增消息表——首页提醒卡片直接读该类型的未读消息（见 MessageController）。
CREATE TABLE qwt_venue_status_watchers (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    deleted    boolean NOT NULL,
    user_id    bigint NOT NULL,
    venue_id   bigint NOT NULL
);
CREATE UNIQUE INDEX qwt_idx_venue_status_watchers_user_venue
    ON qwt_venue_status_watchers (user_id, venue_id);
CREATE INDEX qwt_idx_venue_status_watchers_venue
    ON qwt_venue_status_watchers (venue_id);
