-- ============================================================================
-- V1: Baseline schema（与 JPA 实体映射严格一致的权威建表 DDL）
--
-- 背景（2026-08-07 引入 Flyway 替代 ddl-auto:update，根因见 AGENTS.md「Schema
-- 演进与数据库完整性」）：本脚本是**当前库结构的权威快照**。
-- - 对**已有库**（生产/开发，schema 非空）：Flyway `baseline-on-migrate`
--   将 V1 标记为基线（跳过执行），从 V2 起应用增量迁移——已有表零影响；
-- - 对**全新环境**（空库）：本脚本按序执行，一次性建成与实体映射一致的全量结构。
--
-- 硬性约定（新增表/列一律走后续 V{n} 迁移脚本，禁止再依赖 ddl-auto 自动演进）：
-- 1. 列名/类型/可空/默认值与 JPA 实体声明一致（Hibernate 物理命名 = 驼峰→下划线）
-- 2. 默认值仅由 @ColumnDefault 声明通道派生（字符串枚举带引号，如 'PENDING'）
-- 3. 索引/唯一约束名称与实体 @Index / @UniqueConstraint 一致（Hibernate 生成同名对象）
-- 4. 主键统一 `bigint GENERATED BY DEFAULT AS IDENTITY`（与 GenerationType.IDENTITY
--    及 SchemaIntegrityChecker 的 identity 校验契约一致）
-- 5. 时间列统一 `timestamp(6)` / `time(6)`（Hibernate 对 LocalDateTime/LocalTime 的
--    PostgreSQL 默认映射）
-- ============================================================================

-- ── 用户 ─────────────────────────────────────────────────────────────────────
CREATE TABLE qwt_users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    deleted    boolean NOT NULL,
    open_id    varchar(64)  NOT NULL,
    nickname   varchar(64),
    avatar_url varchar(500),
    role       varchar(20)  NOT NULL
);
CREATE UNIQUE INDEX qwt_idx_users_open_id ON qwt_users (open_id);

-- ── 场所 ─────────────────────────────────────────────────────────────────────
CREATE TABLE qwt_venues (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    deleted         boolean NOT NULL,
    name            varchar(100) NOT NULL,
    status          varchar(20)  NOT NULL DEFAULT 'OPEN',
    image_url       varchar(500),
    photos          varchar(5000),
    description     varchar(500),
    city            varchar(50)  NOT NULL,
    district        varchar(50),
    address         varchar(200),
    longitude       double precision,
    latitude        double precision,
    afternoon_open  time(6),
    afternoon_close time(6),
    evening_open    time(6),
    evening_close   time(6),
    tickets         varchar(2000),
    partner_fees    varchar(1000),
    contact_phone   varchar(20),
    wechat_qr       varchar(500),
    tags            varchar(500),
    sort_weight     integer NOT NULL DEFAULT 0,
    claimed_by      bigint
);
CREATE INDEX qwt_idx_city ON qwt_venues (city);
CREATE INDEX qwt_idx_district ON qwt_venues (district);
CREATE INDEX qwt_idx_status ON qwt_venues (status);
CREATE INDEX qwt_idx_sort_weight ON qwt_venues (sort_weight);
CREATE INDEX qwt_idx_claimed_by ON qwt_venues (claimed_by);

-- ── 场所营业状态变迁日志（无 deleted，独立主键，不继承 BaseEntity） ─────────
CREATE TABLE qwt_venue_status_logs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id    bigint NOT NULL,
    from_status varchar(20),
    to_status   varchar(20) NOT NULL,
    changed_by  bigint,
    created_at  timestamp(6)
);
CREATE INDEX qwt_idx_status_logs_venue_time ON qwt_venue_status_logs (venue_id, created_at);

-- ── 场所浏览记录（按天去重；匿名 userId 可空） ─────────────────────────────
CREATE TABLE qwt_venue_views (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id   bigint NOT NULL,
    user_id    bigint,
    view_date  date NOT NULL,
    created_at timestamp(6)
);
CREATE INDEX qwt_idx_venue_views_venue_date ON qwt_venue_views (venue_id, view_date);
CREATE INDEX qwt_idx_venue_views_user ON qwt_venue_views (user_id);
CREATE UNIQUE INDEX qwt_uq_venue_views_dedup ON qwt_venue_views (venue_id, user_id, view_date);

-- ── 场所动态（公告/通知） ────────────────────────────────────────────────────
CREATE TABLE qwt_venue_posts (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp(6),
    updated_at     timestamp(6),
    deleted        boolean NOT NULL,
    venue_id       bigint NOT NULL,
    title          varchar(100) NOT NULL,
    content        varchar(2000) NOT NULL,
    publisher_type varchar(20) NOT NULL,
    publisher_name varchar(64)
);
CREATE INDEX qwt_idx_posts_venue_id ON qwt_venue_posts (venue_id);
CREATE INDEX qwt_idx_posts_created_at ON qwt_venue_posts (created_at);
CREATE INDEX qwt_idx_posts_venue_deleted ON qwt_venue_posts (venue_id, deleted);

-- ── 场所 Reaction（每日一记模型） ────────────────────────────────────────────
CREATE TABLE qwt_venue_reactions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    deleted       boolean NOT NULL,
    user_id       bigint NOT NULL,
    venue_id      bigint NOT NULL,
    reaction_code varchar(30) NOT NULL,
    reaction_date date NOT NULL
);
CREATE INDEX qwt_idx_vr_venue_code ON qwt_venue_reactions (venue_id, reaction_code);
CREATE INDEX qwt_idx_vr_venue_code_created ON qwt_venue_reactions (venue_id, reaction_code, created_at);
CREATE INDEX qwt_idx_vr_user_id ON qwt_venue_reactions (user_id);
CREATE UNIQUE INDEX qwt_uk_vr_user_venue_code_date
    ON qwt_venue_reactions (user_id, venue_id, reaction_code, reaction_date);

-- ── 场所分享事件日志（只追加，无唯一约束） ──────────────────────────────────
CREATE TABLE qwt_venue_shares (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id   bigint NOT NULL,
    user_id    bigint,
    event_type varchar(16) NOT NULL,
    channel    varchar(16),
    share_from bigint,
    created_at timestamp(6)
);
CREATE INDEX qwt_idx_venue_shares_venue_time ON qwt_venue_shares (venue_id, created_at);
CREATE INDEX qwt_idx_venue_shares_user ON qwt_venue_shares (user_id);
CREATE INDEX qwt_idx_venue_shares_from ON qwt_venue_shares (share_from);

-- ── 场所实时状态报告（upsert 语义，(userId, venueId) 唯一） ──────────────────
CREATE TABLE qwt_venue_status_reports (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    deleted     boolean NOT NULL,
    venue_id    bigint NOT NULL,
    user_id     bigint NOT NULL,
    reason      varchar(20) NOT NULL,
    occurred_at timestamp(6),
    note        varchar(500)
);
CREATE INDEX qwt_idx_status_reports_venue_created ON qwt_venue_status_reports (venue_id, created_at);
CREATE INDEX qwt_idx_status_reports_user ON qwt_venue_status_reports (user_id);
CREATE UNIQUE INDEX qwt_uk_status_report_user_venue ON qwt_venue_status_reports (user_id, venue_id);

-- ── 用户上报（异步审核；userId 可空 = 匿名，2026-08-06 放宽） ────────────────
CREATE TABLE qwt_venue_feedbacks (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    deleted     boolean NOT NULL,
    venue_id    bigint NOT NULL,
    user_id     bigint,
    type        varchar(20) NOT NULL,
    note        varchar(500),
    status      varchar(20) NOT NULL DEFAULT 'PENDING',
    handled_by  bigint,
    handled_at  timestamp(6),
    handle_note varchar(500),
    handled     boolean NOT NULL DEFAULT false
);
CREATE INDEX qwt_idx_feedbacks_venue_id ON qwt_venue_feedbacks (venue_id);
CREATE INDEX qwt_idx_feedbacks_user_id ON qwt_venue_feedbacks (user_id);
CREATE INDEX qwt_idx_feedbacks_status_created ON qwt_venue_feedbacks (status, created_at);

-- ── 收藏（软删恢复模型，(userId, venueId) 唯一） ─────────────────────────────
CREATE TABLE qwt_favorites (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    deleted    boolean NOT NULL,
    user_id    bigint NOT NULL,
    venue_id   bigint NOT NULL
);
CREATE INDEX qwt_idx_fav_user_id ON qwt_favorites (user_id);
CREATE INDEX qwt_idx_fav_venue_id ON qwt_favorites (venue_id);
CREATE INDEX qwt_idx_fav_venue_deleted ON qwt_favorites (venue_id, deleted);
CREATE UNIQUE INDEX qwt_uk_fav_user_venue ON qwt_favorites (user_id, venue_id);

-- ── 评分交互（一用户一场所一维度一行） ───────────────────────────────────────
CREATE TABLE qwt_tag_interactions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    deleted    boolean NOT NULL,
    user_id    bigint NOT NULL,
    venue_id   bigint NOT NULL,
    tag        varchar(50) NOT NULL,
    score      integer
);
CREATE INDEX qwt_idx_ti_venue_tag ON qwt_tag_interactions (venue_id, tag);
CREATE INDEX qwt_idx_ti_user_id ON qwt_tag_interactions (user_id);
CREATE INDEX qwt_idx_ti_venue_tag_updated ON qwt_tag_interactions (venue_id, tag, updated_at);
CREATE UNIQUE INDEX qwt_uk_ti_user_venue_tag ON qwt_tag_interactions (user_id, venue_id, tag);

-- ── 舞伴 ─────────────────────────────────────────────────────────────────────
CREATE TABLE qwt_dancers (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    deleted    boolean NOT NULL,
    nickname   varchar(30) NOT NULL,
    avatar_url varchar(500),
    bio        varchar(300),
    gender     varchar(20),
    status     varchar(20) NOT NULL DEFAULT 'PENDING',
    created_by bigint NOT NULL,
    city       varchar(50)
);
CREATE INDEX qwt_idx_dancers_status ON qwt_dancers (status);
CREATE INDEX qwt_idx_dancers_created_by ON qwt_dancers (created_by);
CREATE INDEX qwt_idx_dancers_city ON qwt_dancers (city);

-- ── 舞伴认可（每日一记模型，(userId, dancerId, recognitionDate) 唯一） ───────
CREATE TABLE qwt_dancer_recognitions (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    deleted          boolean NOT NULL,
    user_id          bigint NOT NULL,
    dancer_id        bigint NOT NULL,
    recognition_date date NOT NULL
);
CREATE INDEX qwt_idx_dr_dancer_date ON qwt_dancer_recognitions (dancer_id, recognition_date);
CREATE INDEX qwt_idx_dr_dancer_created ON qwt_dancer_recognitions (dancer_id, created_at);
CREATE INDEX qwt_idx_dr_user ON qwt_dancer_recognitions (user_id);
CREATE UNIQUE INDEX qwt_uk_dr_user_dancer_date
    ON qwt_dancer_recognitions (user_id, dancer_id, recognition_date);

-- ── 舞伴认可标签（(recognitionId, tag) 唯一） ────────────────────────────────
CREATE TABLE qwt_dancer_recognition_tags (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    deleted       boolean NOT NULL,
    recognition_id bigint NOT NULL,
    dancer_id     bigint NOT NULL,
    user_id       bigint NOT NULL,
    tag           varchar(50) NOT NULL
);
CREATE INDEX qwt_idx_drt_dancer_tag ON qwt_dancer_recognition_tags (dancer_id, tag);
CREATE INDEX qwt_idx_drt_dancer_created ON qwt_dancer_recognition_tags (dancer_id, created_at);
CREATE INDEX qwt_idx_drt_recognition ON qwt_dancer_recognition_tags (recognition_id);
CREATE UNIQUE INDEX qwt_uk_drt_recognition_tag ON qwt_dancer_recognition_tags (recognition_id, tag);

-- ── 舞伴↔舞厅关系（(dancerId, venueId, relation) 唯一） ──────────────────────
CREATE TABLE qwt_dancer_venues (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    deleted    boolean NOT NULL,
    dancer_id  bigint NOT NULL,
    venue_id   bigint NOT NULL,
    relation   varchar(20) NOT NULL,
    note       varchar(200)
);
CREATE INDEX qwt_idx_dv_dancer ON qwt_dancer_venues (dancer_id);
CREATE INDEX qwt_idx_dv_venue ON qwt_dancer_venues (venue_id);
CREATE UNIQUE INDEX qwt_uk_dv_dancer_venue_relation ON qwt_dancer_venues (dancer_id, venue_id, relation);
