-- ── V20：舞伴分享事件日志（qwt_dancer_shares，2026-08-13 新增） ─────────────
-- 需求（用户）：门店详情页可分享门店（qwt_venue_shares 分享闭环），舞伴详情页
-- 同样需要可分享舞伴主页——补齐与场所分享对等的完整闭环：分享动作上报（SHARE）、
-- 分享卡片回流归因（OPEN，路径携带 share_from=<分享者uid>）。
--
-- 设计要点（镜像 qwt_venue_shares，仅目标列不同）：
-- 1. 一张表承载两类事件（event_type 区分，枚举与场所分享共享 ShareEventType）：
--    - SHARE — 分享动作：actor=分享者（user_id），channel=发起渠道
--      （BUTTON / MENU / TIMELINE）；
--    - OPEN — 被分享者打开舞伴详情页：actor=打开者（user_id），
--      share_from=原分享者（回流归因）。
-- 2. 无唯一约束（事件日志语义：每次分享 / 打开都是一条独立事件，天然可 append）；
-- 3. 匿名用户 user_id 为 null，仅参与 IP 频控，不参与身份归因；
-- 4. 分享维度不在热度公式闭集内（与场所分享同语义），本表仅作分析数据源。
CREATE TABLE qwt_dancer_shares (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dancer_id  bigint NOT NULL,
    user_id    bigint,
    event_type varchar(16) NOT NULL,
    channel    varchar(16),
    share_from bigint,
    created_at timestamp(6)
);
CREATE INDEX qwt_idx_dancer_shares_dancer_time ON qwt_dancer_shares (dancer_id, created_at);
CREATE INDEX qwt_idx_dancer_shares_user ON qwt_dancer_shares (user_id);
CREATE INDEX qwt_idx_dancer_shares_from ON qwt_dancer_shares (share_from);
