-- ── V22：运营配置表 + Reaction 每日一票数据卫生（2026-08-14 新增） ──────
-- 需求（用户）：列表页 Reaction 表情"每天只能选择唯一一个他认为最好的表情"，
-- 且该规则由运营可配置（管理员 FAB 菜单「运营配置」开关，即时生效）。
--
-- 根因：唯一约束 (user_id, venue_id, reaction_code, reaction_date) 允许同一用户
-- 同一天对同一场所贡献多个不同 code 的 Reaction——用户可零成本"全选"（chip 快捷
-- 参与 + Picker 多选均无约束），各场所计数同步膨胀、分布趋同，列表 chip 看不出
-- 差别（选择退化为确认，信号被稀释）。修复 = 把稀缺性还给写入模型（每日一票）。
--
-- 设计要点：
-- 1. qwt_ops_config：通用键值运营配置表（feature flag 设施）。首个 key =
--    reaction.daily.single（"每日唯一表情"开关，默认 'true' = 一票制生效）；
--    主键沿用项目惯例 IDENTITY（SchemaIntegrityChecker 统一校验），
--    key 承载唯一约束（qwt_uk_ops_config_key）；
-- 2. 一票约束为**应用层语义**（VenueReactionService 换票事务 + pg_advisory_xact_lock
--    串行化并发），不建 DB 唯一约束——保证运营可即时关闭开关恢复多选
--    （配置驱动的代码路径，数据层不硬编码产品规则）；
-- 3. 数据卫生：清理历史"同日同用户同场所多行"数据（保留每 (user_id, venue_id,
--    reaction_date) 的 max(id) = 最后一次点击意图）——开启一票制后当日查询
--    至多一行，四窗口计数本地 ±1 恢复精确（换票 = 旧 code -1 + 新 code +1）；
-- 4. 本清理为一次性 Flyway 迁移（幂等）；seed-dev.sql 同步去除同日多行演示数据。
CREATE TABLE qwt_ops_config (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key        varchar(64) NOT NULL,
    value      varchar(255) NOT NULL,
    updated_by bigint,
    updated_at timestamp(6)
);

CREATE UNIQUE INDEX qwt_uk_ops_config_key ON qwt_ops_config (key);

INSERT INTO qwt_ops_config (key, value, updated_by, updated_at)
VALUES ('reaction.daily.single', 'true', NULL, now());

DELETE FROM qwt_venue_reactions
WHERE id NOT IN (
    SELECT MAX(id) FROM qwt_venue_reactions
    GROUP BY user_id, venue_id, reaction_date
);
