-- ============================================================================
-- V23: 积分门槛与解锁记录（2026-08-14，舞伴照片/联系方式"积分解锁"公共模块）
--
-- 背景（需求：舞伴上传的每张照片、联系方式都可自由设置"是否需要积分查看、
-- 支付多少积分"；且这是**公共模块**——未来任何"内容点"都可声明积分门槛）：
-- 统一模型 = 门槛（qwt_points_gates，target_type + target_id + cost）+ 解锁
-- （qwt_points_unlocks，user_id + target_type + target_id）。
--
-- 合规决策（核心，2026-08-14 定稿）：
-- 解锁消耗的积分**单向燃烧（burn）**，不进入目标舞伴账户——若转移到舞伴账户，
-- 舞伴可再花掉，即形成"用户A → 舞伴B → B再消费"的资产转移链条，触碰
-- "可流转准货币"合规红线（与 2026-08-12 礼物化根因同源：礼物不可回收、
-- 不可再流转，彻底切断资产转移链条）。积分 = 单向消耗品：只能"解锁内容 /
-- 购买礼物送出"。舞伴获得的回报是"有人愿为 TA 的内容花积分"的社会证明
-- （unlocks 表天然支持解锁人数统计，本期不做展示，预留给后续）。
--
-- 设计要点：
-- 1. qwt_points_gates：cost > 0 才落行（"存在行"即"有门槛"）；清除门槛 =
--    软删行（部分唯一索引 WHERE deleted = false，兼容软删后重建）；
--    created_by/updated_by 记录设置者（舞伴本人/管理员），审计用。
-- 2. qwt_points_unlocks：一人一目标只扣一次费（UNIQUE(user_id,target_type,
--    target_id)，SQLState 23505 幂等兜底并发）；transaction_id 关联扣费流水，
--    审计闭环。
-- ============================================================================

-- ── 积分门槛（目标 → 所需积分；cost>0 才落行） ────────────────────────────
CREATE TABLE qwt_points_gates (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    deleted     boolean NOT NULL,
    target_type varchar(30) NOT NULL,
    target_id   bigint NOT NULL,
    cost        integer NOT NULL,
    created_by  bigint NOT NULL,
    updated_by  bigint
);
-- 部分唯一索引：软删行不占位，门槛清除（软删）后可重新设置
CREATE UNIQUE INDEX qwt_uk_points_gates_target
    ON qwt_points_gates (target_type, target_id)
    WHERE deleted = false;
-- 解锁统计/管理端巡检走目标维度
CREATE INDEX qwt_idx_points_gates_target_type
    ON qwt_points_gates (target_type, target_id, deleted);

-- ── 解锁记录（谁解锁了什么；一人一目标只扣一次费） ────────────────────────
CREATE TABLE qwt_points_unlocks (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp(6),
    user_id        bigint NOT NULL,
    target_type    varchar(30) NOT NULL,
    target_id      bigint NOT NULL,
    transaction_id bigint NOT NULL
);
CREATE UNIQUE INDEX qwt_uk_points_unlocks_user_target
    ON qwt_points_unlocks (user_id, target_type, target_id);
CREATE INDEX qwt_idx_points_unlocks_target
    ON qwt_points_unlocks (target_type, target_id);
