-- ============================================================================
-- V25: 舞伴相册模糊图 + 创作者收益计划（2026-08-14）
--
-- 1. qwt_dancer_photos.blur_url（需求：收费照片详情页展示"模糊可见轮廓"占位，
--    参考 Telegram 打遮罩语义）——未解锁用户仅拿到模糊图（低分辨率不可还原），
--    原图 url 仍不下发（防绕过，见 AGENTS.md「积分解锁」）。模糊图由前端
--    上传原图时用 canvas 离屏降采样生成并随原图一起上传（blurUrls）。
--
-- 2. qwt_dancers.earnings_enabled（创作者收益计划开关，2026-08-14）：
--    开启后舞伴详情页接入微信小程序激励视频广告（用户主动观看支持 TA），
--    收益由平台线下转账结算（MVP 无线上结算）。新 NOT NULL 列唯一通道 =
--    @ColumnDefault（见 AGENTS.md「Schema 演进」）。
--
-- 3. qwt_dancer_ad_views（广告观看记录——线下结算依据 + 防刷锚点）：
--    UNIQUE(user_id, dancer_id, view_date) 同一用户同舞伴每天至多支持一次
--    （防刷；SQLState 23505 幂等返回已有计数）。
-- ============================================================================
ALTER TABLE qwt_dancer_photos ADD COLUMN blur_url varchar(500);

ALTER TABLE qwt_dancers ADD COLUMN earnings_enabled boolean NOT NULL DEFAULT false;

CREATE TABLE qwt_dancer_ad_views (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    dancer_id  bigint NOT NULL,
    user_id    bigint NOT NULL,
    view_date  date NOT NULL
);
CREATE UNIQUE INDEX qwt_uk_ad_views_user_dancer_date
    ON qwt_dancer_ad_views (user_id, dancer_id, view_date);
CREATE INDEX qwt_idx_ad_views_dancer ON qwt_dancer_ad_views (dancer_id);
