-- ============================================================================
-- V26: 舞伴官方认证（信息核验标识）——2026-08-14
--
-- 治理语义（见 docs/agents 09「舞伴官方认证」）：
--   「信息核验」= 舞伴身份与公开信息经平台人工核验属实（裁决事实，不裁决人品）；
--   认证是可回退的信任背书，不是一次性授予永久生效。
--
-- 1. qwt_dancers 三列（当前认证快照；历史变迁全量在审计日志表）：
--    verification_status：UNVERIFIED（默认）/ VERIFIED / PENDING_REVIEW（待复核）
--    verified_at / verified_by：最近一次授予认证的时间与管理员（非 VERIFIED 时为 NULL，
--    审计靠日志表，快照只服务当前展示）。
--
-- 2. qwt_dancer_verification_logs（审计日志，参照 qwt_venue_status_logs 模式）：
--    每次状态变迁一行（from_status → to_status），记录操作人 operator_id
--    （授予/撤销 = 管理员；编辑触发待复核 = 编辑者本人）与 reason（撤销必填——
--    延续"被指涉方有申辩权"：被撤销舞伴可查原因）。
--
-- 护栏（"防认证挂在过期信息上"）：舞伴本人编辑资料 → VERIFIED 自动降级
-- PENDING_REVIEW（曾认证被撤销后编辑亦触发，重新核验闭环）；管理员直改不触发
-- （管理者已在该资料上进行管理动作，避免制造待办噪音）。
-- ============================================================================
ALTER TABLE qwt_dancers ADD COLUMN verification_status varchar(20) NOT NULL DEFAULT 'UNVERIFIED';
ALTER TABLE qwt_dancers ADD COLUMN verified_at timestamp(6);
ALTER TABLE qwt_dancers ADD COLUMN verified_by bigint;

CREATE TABLE qwt_dancer_verification_logs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    dancer_id   bigint NOT NULL,
    operator_id bigint,
    from_status varchar(20) NOT NULL,
    to_status   varchar(20) NOT NULL,
    reason      varchar(200)
);
CREATE INDEX qwt_idx_verification_logs_dancer ON qwt_dancer_verification_logs (dancer_id);
