-- ============================================================================
-- V27: 舞伴收藏（qwt_dancer_favorites）——2026-08-14
--
-- 背景与根因（见 docs/agents 09「舞伴收藏」）：门店收藏体系（qwt_favorites +
-- FavoriteService + venue-detail 星标）是**场所域特化**的——表结构
-- venue_id NOT NULL + UNIQUE(user_id, venue_id)、接口返回 VenueResponse、
-- 收藏列表联查 qwt_favorites→qwt_venues。舞伴域从未获得"收藏"能力
-- （无表/无接口/详情页无星标），导致舞伴列表页结构上不可能有「收藏」Tab——
-- 双 Tab 不是页面层选择，而是领域能力决定的上层建筑。
--
-- 设计决策：
-- 1. **独立表而非多态化 qwt_favorites**：qwt_favorites 与热度趋势 SQL
--    （unfavorited_at 按日分组、收藏总数/近30天新增为热度公式输入）及
--    VenueResponse 返回类型深度耦合，多态化改造（target_type 列 +
--    unique 约束迁移 + 趋势 SQL 过滤）风险远大于收益。按"1 领域 1 表"显式
--    建模，与舞伴域既有模式（qwt_dancer_photos 独立表不复用 venue.photos）
--    一致。
-- 2. **无频控**：门店收藏的 Caffeine 60s 阈值频控根因是"取消收藏每次写
--    unfavorited_at 会刷高趋势折线"；舞伴收藏不输入任何趋势图，无膨胀风险，
--    只需幂等（唯一约束 + 软删恢复）即可。
-- 3. **收藏列表仅含当前公开舞伴**（d.status='NORMAL' AND d.deleted=false）：
--    HIDDEN 是可见性开关（下架=退出公众视野），被收藏后下架的舞伴自动淡出
--    收藏列表（行保留，恢复 NORMAL 后自动重现）——收藏的是"当前可见的内容"。
--
-- 数据模型（仿 qwt_favorites 的软删 + 唯一约束模式）：
--   UNIQUE(user_id, dancer_id)：软删行可被重新收藏复用（restore 语义，
--   与门店收藏恢复逻辑一致）。
-- ============================================================================
CREATE TABLE qwt_dancer_favorites (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    deleted    boolean NOT NULL DEFAULT false,
    user_id    bigint NOT NULL,
    dancer_id  bigint NOT NULL
);

CREATE UNIQUE INDEX qwt_uk_dancer_fav_user_dancer ON qwt_dancer_favorites (user_id, dancer_id);
CREATE INDEX qwt_idx_dancer_fav_user ON qwt_dancer_favorites (user_id);
CREATE INDEX qwt_idx_dancer_fav_dancer ON qwt_dancer_favorites (dancer_id);
