-- ============================================================================
-- V29: 舞伴浏览记录（qwt_dancer_views）——2026-08-14
--
-- 背景（舞伴统计图第一期，见前端 docs/agents/09「舞伴统计」）：
-- 舞伴详情页此前无浏览埋点（门店有 qwt_venue_views 支撑浏览趋势/浏览来源两张
-- 统计图，舞伴域从未记录详情页打开）。本期引入浏览埋点，支撑：
--   1. 浏览趋势（每日浏览数，含匿名）；
--   2. 浏览来源（list/share/search/other 分列，对齐门店 ViewSource 语义）。
--
-- 设计决策（完全镜像 qwt_venue_views + V18/V21 教训，勿重蹈）：
-- 1. **独立表而非多态化 qwt_venue_views**：门店浏览表与热度趋势 SQL
--    （countDailyTrends 按 source 分组）及 VenueHeatService 深度耦合，
--    多态化改造（target_type 列）风险远大于收益——按"1 领域 1 表"显式建模，
--    与舞伴域既有模式（qwt_dancer_favorites 独立表）一致。
-- 2. **去重粒度 = 按天按来源**：唯一索引 qwt_uq_dancer_views_dedup 含 source
--    列——同一用户同一舞伴同一天每个来源至多一条（多渠道独立计数互不覆盖，
--    对齐门店 V21 产品决策：搜索/列表是不同流量）；匿名 userId=NULL 不受唯一
--    索引约束（UNIQUE 视 NULL 互不相等），每次访问均记录，60s IP 频控兜底。
-- 3. **source 默认 OTHER**：@ColumnDefault 唯一声明通道（枚举类列不加 CHECK，
--    项目约定），兼容旧客户端未上报来源的存量写入。
-- 4. **upsert 必须用 ON CONFLICT (列清单) 列推断**（门店 V21 根因教训：
--    ON CONFLICT ON CONSTRAINT 只匹配约束、不匹配 CREATE UNIQUE INDEX，
--    生产库保持索引形态时每次写入抛错且被 fire-and-forget 静默吞掉）——
--    DancerViewRepository.upsertView 的冲突目标与本索引列清单一致。
-- ============================================================================
CREATE TABLE qwt_dancer_views (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dancer_id  bigint NOT NULL,
    user_id    bigint,
    view_date  date NOT NULL,
    source     varchar(16) NOT NULL DEFAULT 'OTHER',
    created_at timestamp(6)
);

CREATE UNIQUE INDEX qwt_uq_dancer_views_dedup ON qwt_dancer_views (dancer_id, user_id, view_date, source);
CREATE INDEX qwt_idx_dancer_views_dancer_date ON qwt_dancer_views (dancer_id, view_date);
CREATE INDEX qwt_idx_dancer_views_user ON qwt_dancer_views (user_id);
CREATE INDEX qwt_idx_dancer_views_source ON qwt_dancer_views (dancer_id, view_date, source);
