-- ============================================================================
-- V29: 舞伴多城市 + 联系方式图片（2026-08-14）
--
-- 需求（新增舞伴表单三项改造，见 docs/agents 09「舞伴资料表单」）：
-- ① 城市改为城市选择器（默认定位当前城市，最多 3 个城市）；
-- ② 联系方式可上传图片（二维码等）；
-- ③ 删除性别列（性别恒「女」不可操作，提交恒 FEMALE——纯前端收敛，无 Schema 变更）。
--
-- 一、联系方式图片（contact_image_url）
--    舞伴联系方式 = 文本（contact，V24）+ 图片（contact_image_url，本迁移新增）。
--    属于舞伴资料一部分，随 UpsertDancerRequest 走既有 PENDING 审核流程；
--    详情页与 contact 同一可见性（遮挡/门槛/解锁三态一致，见 DancerService#getDetail）；
--    图片 URL 入库前必须经 storage/ImageContentValidator 内容校验（08-12 安全加固约定）。
--    列默认值唯一声明通道 = @ColumnDefault（实体 Dancer.contactImageUrl，无默认 = 可空）。
--
-- 二、多城市子表（qwt_dancer_cities）
--    背景：舞伴是自然人，可能常驻/活跃于多个城市。原 dancer.city 单列只能表达
--    一个城市，无法承载"最多 3 个城市"需求。设计决策：
--    - 独立子表而非多态化/JSON 列：城市是"可多值、按序、可编辑替换"的集合，
--      子表与既有 DancerVenue（舞伴↔舞厅多对多）同模式，SQL 筛选/聚合直接；
--      禁逗号拼接 hack（见 AGENTS.md 编码规范）。
--    - dancer.city 保留为主城市（= cities 第一个，service 单一写入方）：
--      列表/详情/分享的展示位与既有列表 SQL（排序、封面、筛选）零改动，
--      属派生冗余（同 venue 域 city+district 冗余展示字段先例）。
--    - 无唯一约束（对齐 DancerVenue 先例）：编辑 = 软删旧行 + 插入新行，
--      幂等去重由 service 代码保证（防唯一约束与软删行冲突）。
--    - 存量回填：既有 dancer.city 补进子表（sort_order=0），词表/筛选无缝覆盖旧数据。
-- ============================================================================
ALTER TABLE qwt_dancers ADD COLUMN contact_image_url varchar(500);

CREATE TABLE qwt_dancer_cities (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    deleted    boolean NOT NULL DEFAULT false,
    dancer_id  bigint NOT NULL,
    city       varchar(50) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0
);

CREATE INDEX qwt_idx_dancer_cities_dancer ON qwt_dancer_cities (dancer_id);
CREATE INDEX qwt_idx_dancer_cities_city ON qwt_dancer_cities (city);

-- 存量回填：既有单城市舞伴补进子表（列表筛选/城市词表无缝覆盖）
INSERT INTO qwt_dancer_cities (dancer_id, city, sort_order)
SELECT d.id, d.city, 0
FROM qwt_dancers d
WHERE d.city IS NOT NULL AND d.city <> '' AND d.deleted = false;
