-- ============================================================================
-- V33: 舞友群（qwt_group_chats，2026-08-17）
--
-- 需求（运营引流入微信群）：小程序内提供"加入舞友群"入口，运营可配置多个
-- 群聊，维度 = 全国 / 城市 / 地域。
--
-- 根因（为什么是"长按识别二维码"而不是"一键加群"）：
-- 微信小程序平台**没有**提供"程序内直接拉起加入微信群"的开放能力——与群相关的
-- 开放能力仅有分享到群（shareAppMessage / shareTicket，分享链接非加群），
-- 加群动作的唯一发起通道是**群二维码**（长按识别 / 扫一扫）。这是平台安全模型
-- 的刻意设计（防小程序滥用跳转骚扰、防拉人脚本），任何小程序（含腾讯自家产品）
-- 的"一键加群"本质都是"展示群二维码 + 引导长按识别"。
-- 因此本功能的正确实现 = `<image show-menu-by-longpress>` 长按识别 + 点击放大预览
-- 降级（previewImage 内同样可长按识别）。群二维码存在天然失效场景（7 天有效期、
-- 扫码进群满 200 人失效）——运营管理端可随时更换二维码图片（qr_code_url 可编辑）。
--
-- 设计要点：
-- 1. scope 三态维度：NATIONWIDE（全国）/ CITY（城市，city 必填）/ REGION（地域，
--    region 必填，运营自定义地域名如「长三角」）。city / region 按维度**互斥必填**，
--    服务端统一校验（枚举类列禁 CHECK，Java enum 语义，扩维度免迁移）。
-- 2. 展示开关双层：enabled（上下线，运营临时下架不删数据）+ deleted（BaseEntity
--    软删，彻底移除记录）。公开读仅返回 enabled=true AND deleted=false。
-- 3. display_order：运营手动排序（公开列表按 display_order, id 稳定排序），
--    同 scope 内排序，跨 scope 展示顺序由前端按 全国→城市→地域 固定。
-- 4. qr_code_url 属"新增图片 URL 落库字段"，必须挂 storage/ImageContentValidator
--    内容校验（08-12 安全加固约定：public 桶前缀防 SSRF → ≤5MB → magic bytes →
--    宽高防解压炸弹）；管理端上传经 FileCategory.GROUP_QR（豁免二次压缩）。
-- 5. updated_by 记录最近操作管理员（对齐 OpsConfig 先例，审计运营操作）。
-- 6. 无唯一约束：同一城市/维度允许多个群（运营按活跃度可配置多群分流）。
-- ============================================================================
CREATE TABLE qwt_group_chats (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    deleted       boolean NOT NULL DEFAULT false,
    name          varchar(64) NOT NULL,
    scope         varchar(20) NOT NULL,
    city          varchar(50),
    region        varchar(50),
    qr_code_url   varchar(500) NOT NULL,
    description   varchar(200),
    display_order integer NOT NULL DEFAULT 0,
    enabled       boolean NOT NULL DEFAULT true,
    updated_by    bigint
);

CREATE INDEX qwt_idx_group_chats_scope_deleted ON qwt_group_chats (scope, deleted);
CREATE INDEX qwt_idx_group_chats_city_deleted ON qwt_group_chats (city, deleted);
