-- ============================================================================
-- V35: 门店相册照片（照片级"先审后发"审核闸门 + UGC 上传通道）
--
-- 背景（2026-08-20，根因：门店相册基本无照片）：
-- 旧模型 venue.photos 为 JSON 数组列——只能经"创建/编辑门店"整表提交时全量覆盖
-- （写权限 = 认领人/管理员），无法表达"任意时刻、任意用户、逐张、带审核状态"
-- 的照片；又因无审核闸门不敢向普通用户开放上传 → 到店用户（最大照片贡献来源）
-- 零通道 → 照片数据趋近于零（AGENTS.md「门店照片域」根因链 R1/R2/R3）。
-- 本迁移将门店照片升级为独立实体，完整复用舞伴照片（qwt_dancer_photos，
-- V7）已验证的模式：独立表 + PENDING 先审后发 + sortOrder 上传序 + 管理端审核。
-- 与舞伴照片的差异：门店照片无收费解锁需求，故无 blur_url 列；写者开放给
-- 任意登录用户（管理方直发 PUBLIC，普通用户 PENDING）。
--
-- 存量数据：一次性把 venue.photos JSON 数组元素灌入新表（status=PUBLIC，
-- created_by 回填认领人，无认领置 0 表示存量导入），随后读路径整体切换
-- 新表、venue.photos JSON 列废弃不再写入（残留数据保留以便回滚，见 AGENTS.md）。
-- 列定义与 JPA 实体 VenuePhoto 严格一致（Hibernate 物理命名 = 驼峰→下划线）。
-- ============================================================================
CREATE TABLE qwt_venue_photos (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    deleted    boolean NOT NULL,
    venue_id   bigint NOT NULL,
    url        varchar(500) NOT NULL,
    status     varchar(20) NOT NULL DEFAULT 'PENDING',
    created_by bigint NOT NULL,
    sort_order integer NOT NULL DEFAULT 0
);
CREATE INDEX qwt_idx_vp_venue ON qwt_venue_photos (venue_id);
CREATE INDEX qwt_idx_vp_venue_status ON qwt_venue_photos (venue_id, status);
CREATE INDEX qwt_idx_vp_status_created ON qwt_venue_photos (status, created_at);

-- 存量 JSON 列照片迁移（幂等：仅插入，不清理 JSON 列——读路径切换后可回滚）。
-- jsonb_array_elements_text 展开数组元素；WITH ORDINALITY 保数组序为 sort_order。
-- 防御：仅迁移"数组开头"的合法 JSON 列（serializeStringList 写入恒为合法数组或 null，
-- 此过滤兜底历史手改脏数据，避免 cast 失败阻断迁移）。
INSERT INTO qwt_venue_photos (created_at, updated_at, deleted, venue_id, url, status, created_by, sort_order)
SELECT NOW(), NOW(), false, v.id, elem, 'PUBLIC', COALESCE(v.claimed_by, 0), ord - 1
FROM qwt_venues v,
     LATERAL jsonb_array_elements_text(NULLIF(v.photos, '')::jsonb) WITH ORDINALITY AS t(elem, ord)
WHERE v.deleted = false
  AND v.photos IS NOT NULL
  AND v.photos <> ''
  AND v.photos ~ '^\s*\[';
