-- 通用标签字典 + 舞伴资料标签（2026-08-24）。
-- 背景：舞伴新增/编辑需要一套管理员可扩展的标签系统（线上/线下/龙女…），
-- 且要求「用户长按/点击标签弹出说明」——标签必须携带权威说明文案（description），
-- 因此不能沿用门店「自由文本 JSON 列」方案（无说明、无法扩展），改为字典化：
--   · qwt_tag_dict = 通用标签字典（scope 区分适用领域：DANCER 舞伴 / VENUE 门店预留，
--     门店未来可迁移至本字典，同一套接口即「套用门店标签」的架构落点）；
--   · qwt_dancers.profile_tags = 字典 id 数组（JSON，如 [1,3]），空 = 无标签——
--     存 id 而非 text：标签重命名/改说明不影响历史关联（对齐门店 JSON 列架构先例，
--     仅存储载体升级为稳定 id）。
-- 与「舞伴认可标签」（qwt_dancer_recognition_tags，用户行为产生）语义完全独立：
-- 本字典 = 管理员/运营设置的资料标签（黄页内容，平台代发模型，无 UGC 红线风险）。

CREATE TABLE qwt_tag_dict (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    deleted     boolean NOT NULL DEFAULT false,
    scope       varchar(20)  NOT NULL,
    text        varchar(20)  NOT NULL,
    description varchar(300) NOT NULL DEFAULT '',
    sort_order  int          NOT NULL DEFAULT 0,
    active      boolean      NOT NULL DEFAULT true,
    created_by  bigint
);
CREATE UNIQUE INDEX uk_qwt_tag_dict_scope_text ON qwt_tag_dict (scope, text) WHERE deleted = false;
CREATE INDEX idx_qwt_tag_dict_scope ON qwt_tag_dict (scope, active, sort_order);

-- 舞伴资料标签（2026-08-24）：字典 id 数组 JSON；空 = 无标签。
ALTER TABLE qwt_dancers
    ADD COLUMN profile_tags varchar(500);

-- 初始标签（2026-08-24）：线上 / 线下 / 龙女。
-- 「龙女」说明用「听障舞者版」尊重文案——标签名保留圈内习惯称呼「龙女」，
-- 说明以「听障」替代「聋哑」（现代残障社群认可的表达，用户确认采用）。
INSERT INTO qwt_tag_dict (scope, text, description, sort_order, active) VALUES
('DANCER', '线上', '该舞伴仅提供线上互动服务（如视频连线、线上陪跳），不提供线下见面伴舞。', 1, true),
('DANCER', '线下', '该舞伴以线下见面伴舞为主。', 2, true),
('DANCER', '龙女', '圈内对听障女性舞者的习惯称呼。她们用视觉与身体感受音乐节奏，同样热爱舞蹈。交流时请多些耐心，善用文字和手势，尊重每一份热爱。', 3, true);
