-- ============================================================================
-- V42: 舞伴服务范围 + 联系方式需求记录（2026-08-24）
--
-- 背景（需求：舞伴联系方式获取质量优化——用户不清楚舞伴提供什么服务，
-- 反复询问导致舞伴认为"口嗨"。解法 = 服务信息结构化展示 + 获取联系方式前
-- 必须选择本次需求（服务≤2 + 时间≤2 + 时长可选），自动生成添加好友时的
-- 需求描述，舞伴一眼看懂；需求记录落库供骚扰投诉/异常访问风控）：
--
-- 1. qwt_dancer_services：舞伴服务范围（黄页内容，admin 录入 = 平台代发模型，
--    符合「小程序类目合规 UGC 红线」——非用户 UGC，无公开展示风险）。
--    category 为服务类别枚举（DANCE_HALL 舞厅包时 / KTV KTV包时 /
--    PRIVATE_CINEMA 私影包时 / OTHER 其他场景 / ONLINE 线上服务）；
--    label 为消息拼接用的短标签（admin 可自定义，默认 = 类别名）；
--    price_text / location_scope / advance_notice / rules = 服务信息结构化字段
--    （计费方式 / 地点范围 / 提前预约要求 / 规则与限制），详情页「服务范围」卡展示。
-- 2. qwt_demand_records：联系方式需求记录（user + dancer + 服务 id 列表 +
--    时间槽 + 时长 + 生成的完整消息）。只存枚举/id/短标签，不存自由文本
--    （隐私克制：需求 = 行为数据，非身份信息）；message 冗余整句便于人工审计。
-- ============================================================================

-- ── 舞伴服务范围 ─────────────────────────────────────────────────────────
CREATE TABLE qwt_dancer_services (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp(6),
    updated_at     timestamp(6),
    deleted        boolean NOT NULL DEFAULT false,
    dancer_id      bigint NOT NULL,
    label          varchar(20) NOT NULL,
    category       varchar(20) NOT NULL,
    price_text     varchar(100) NOT NULL DEFAULT '',
    location_scope varchar(100) NOT NULL DEFAULT '',
    advance_notice varchar(100) NOT NULL DEFAULT '',
    rules          varchar(300) NOT NULL DEFAULT '',
    sort_order     integer NOT NULL DEFAULT 0,
    active         boolean NOT NULL DEFAULT true
);
CREATE INDEX idx_qwt_dancer_services_dancer
    ON qwt_dancer_services (dancer_id, active, sort_order);
-- 同一舞伴下标签唯一（软删行不占位，删除后可重建同名服务）
CREATE UNIQUE INDEX uk_qwt_dancer_services_dancer_label
    ON qwt_dancer_services (dancer_id, label)
    WHERE deleted = false;

-- ── 联系方式需求记录（风控留痕，2026-08-24） ─────────────────────────────
CREATE TABLE qwt_demand_records (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    user_id     bigint NOT NULL,
    dancer_id   bigint NOT NULL,
    service_ids varchar(100) NOT NULL,
    time_slots  varchar(50) NOT NULL,
    duration    varchar(20),
    message     varchar(120) NOT NULL DEFAULT ''
);
-- 风控查询：按用户（频繁异常解锁）或按舞伴（骚扰投诉排查）
CREATE INDEX idx_qwt_demand_records_user
    ON qwt_demand_records (user_id, created_at);
CREATE INDEX idx_qwt_demand_records_dancer
    ON qwt_demand_records (dancer_id, created_at);

-- 免费解锁（每日首单免费 / 无门槛舞伴）无扣费流水 → transaction_id 可空
ALTER TABLE qwt_points_unlocks
    ALTER COLUMN transaction_id DROP NOT NULL;
