-- ── V4：站内信（消息中心通用消息，2026-08-08 新增） ─────────────────────────
-- 承载平台对用户的主动通知（当前：舞伴主页审核结果），用户级资源按 user_id 查询。
-- 与「我的上报」（qwt_venue_feedbacks / qwt_venue_status_reports）数据源独立——
-- 上报记录是用户主动动作的业务数据，管理员处理结果经原记录回传（handleNote），
-- 不复制为站内信；二者在前端「消息中心」页面统一展示（见 AGENTS.md「站内信」章节）。
CREATE TABLE qwt_messages (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    deleted      boolean NOT NULL,
    user_id      bigint NOT NULL,
    type         varchar(30) NOT NULL,
    title        varchar(100) NOT NULL,
    content      varchar(500) NOT NULL,
    related_type varchar(30),
    related_id   bigint,
    read_at      timestamp(6)
);
CREATE INDEX qwt_idx_messages_user_created ON qwt_messages (user_id, created_at);
CREATE INDEX qwt_idx_messages_user_read ON qwt_messages (user_id, read_at);
