-- 平台级意见反馈（BUG / 建议 / 夸奖，不绑定门店；2026-08-28 新增）
-- 与 qwt_venue_feedbacks（门店维度上报）并行：本表承载"对整个小程序的意见反馈"，
-- 匿名可提交（user_id 可空），管理端统一在上报管理后台第三 tab 处理。
CREATE TABLE qwt_app_feedbacks (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    deleted     boolean NOT NULL,
    user_id     bigint,
    category    varchar(20) NOT NULL,
    content     varchar(500) NOT NULL,
    image_url   varchar(512),
    status      varchar(20) NOT NULL DEFAULT 'PENDING',
    handled_by  bigint,
    handled_at  timestamp(6),
    handle_note varchar(500)
);
CREATE INDEX qwt_idx_app_feedbacks_user ON qwt_app_feedbacks (user_id);
CREATE INDEX qwt_idx_app_feedbacks_status_created ON qwt_app_feedbacks (status, created_at);
