-- 门店热度上报（舞友上报今晚在店舞伴 / 男客情况，2026-08-29 新增）
-- 设计文档：docs/agents/27-venue-crowd-report.md
--
-- 语义：双维实时众包信号——female_level（在店舞伴女数量档位 1-4，主信号）
-- + male_level（男客密度 1-3，次信号，可空=跳过）。先发后审、不冒充平台权威；
-- 聚合窗口 = 最近 2 小时（CrowdReportService.CROWD_WINDOW_HOURS），过时自动撤下
-- （与门店报告 2 天公示期区分：人数是「此刻」的信号）。
--
-- 防刷（复用 Reaction 每日一记模式）：每人每店每天至多 1 条（report_date 自然日），
-- 同日再次上报 = UPDATE 原行 + modify_count+1（幂等，无积分激励——2026-08-29
-- 用户拍板首版零积分，防「为分而报」污染众包信号）。无撤销功能（纯自然增长），
-- deleted 恒 false；部分唯一索引 WHERE deleted = false 与项目既有模式一致
-- （同 PointsUnlock / qwt_demand_records 部分唯一索引先例）。

CREATE TABLE qwt_venue_crowd_reports (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    deleted       boolean NOT NULL,
    venue_id      bigint NOT NULL,
    user_id       bigint NOT NULL,
    female_level  smallint NOT NULL,
    male_level    smallint,
    report_date   date NOT NULL,
    modify_count  smallint NOT NULL DEFAULT 0
);

-- 部分唯一索引：每人每店每天一票（deleted=false 时唯一，删除后可重新插入）
CREATE UNIQUE INDEX qwt_idx_crowd_reports_user_day
    ON qwt_venue_crowd_reports (venue_id, user_id, report_date)
    WHERE deleted = false;

-- 聚合窗口扫描（最近 2 小时）+ 管理端未来按店聚合
CREATE INDEX qwt_idx_crowd_reports_venue_created
    ON qwt_venue_crowd_reports (venue_id, created_at);
