-- 门店招工（2026-08-29 新增，P0：仅管理员直发，无用户 UGC 通道——个人主体合规红线）
-- 定位 = 用工信息展示（黄页），非招聘服务：无投递/报名/简历闭环。
-- 对外文案规避「招聘」字面（类目机审词族），表名/接口保留 recruitments 技术命名。
-- 字段模型对标真实招工样例（传祺酒馆）：职位多选/人数/合作周期/性别年龄/薪资/待遇/联系双通道/有效期。
-- 刻意不做：残疾限制等就业歧视字段（合规不容纳）；招工描述中的导流话术由发布风险词拦截。
CREATE TABLE qwt_recruitments (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    deleted          boolean NOT NULL,
    venue_id         bigint NOT NULL,
    position_types   varchar(200) NOT NULL,
    headcount        integer,
    term             varchar(20) NOT NULL DEFAULT 'LONG_TERM',
    gender_limit     varchar(10) NOT NULL DEFAULT 'ANY',
    age_min          integer,
    age_max          integer,
    salary_type      varchar(20) NOT NULL DEFAULT 'NEGOTIABLE',
    salary_text      varchar(64),
    accommodation    boolean,
    travel_paid      boolean,
    description      varchar(1000) NOT NULL,
    contact_name     varchar(32),
    contact_phone    varchar(20),
    contact_wechat   varchar(64),
    is_urgent        boolean NOT NULL DEFAULT false,
    status           varchar(20) NOT NULL DEFAULT 'DRAFT',
    published_at     timestamp(6),
    expires_at       timestamp(6) NOT NULL,
    created_by       bigint NOT NULL
);
CREATE INDEX qwt_idx_recruitments_status_expires ON qwt_recruitments (status, expires_at);
CREATE INDEX qwt_idx_recruitments_venue ON qwt_recruitments (venue_id);

-- 联系方式获取留痕（每次获取幂等一记，唯一键 = 招工 + 用户；供管理端「N 人获取」效果反馈）
CREATE TABLE qwt_recruitment_contacts (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    deleted          boolean NOT NULL,
    recruitment_id   bigint NOT NULL,
    user_id          bigint NOT NULL
);
CREATE UNIQUE INDEX qwt_idx_recruitment_contacts_unique ON qwt_recruitment_contacts (recruitment_id, user_id);
