-- 平台授权的资源级权限：全局 ADMIN 负责授权，普通 USER 仅管理明确分配的门店/舞伴。
-- claimed_by / created_by 只保留业务摘要和创建审计语义，存量权限在本迁移中回填。
CREATE TABLE qwt_resource_grants (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    deleted          boolean NOT NULL DEFAULT false,
    version          bigint NOT NULL DEFAULT 0,
    subject_user_id  bigint NOT NULL,
    resource_type    varchar(20) NOT NULL,
    resource_id      bigint NOT NULL,
    status           varchar(20) NOT NULL DEFAULT 'ACTIVE',
    source           varchar(30) NOT NULL DEFAULT 'ADMIN_DIRECT',
    valid_from       timestamp(6),
    valid_until      timestamp(6),
    granted_by       bigint NOT NULL,
    granted_at       timestamp(6) NOT NULL,
    revoked_by       bigint,
    revoked_at       timestamp(6),
    revoke_reason    varchar(200),
    note             varchar(500),
    CONSTRAINT qwt_uk_resource_grant_subject UNIQUE (subject_user_id, resource_type, resource_id)
);
CREATE INDEX qwt_idx_resource_grants_subject ON qwt_resource_grants (subject_user_id, status, valid_until);
CREATE INDEX qwt_idx_resource_grants_resource ON qwt_resource_grants (resource_type, resource_id, status, valid_until);

CREATE TABLE qwt_resource_grant_permissions (
    grant_id          bigint NOT NULL,
    permission_code   varchar(64) NOT NULL,
    PRIMARY KEY (grant_id, permission_code)
);

-- 只追加审计，不继承软删：权限变化、延期、撤销必须可追溯。
CREATE TABLE qwt_resource_grant_audits (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at            timestamp(6),
    grant_id              bigint NOT NULL,
    actor_user_id         bigint NOT NULL,
    action                varchar(30) NOT NULL,
    from_status           varchar(20),
    to_status             varchar(20) NOT NULL,
    before_permissions    varchar(1000),
    after_permissions     varchar(1000) NOT NULL,
    before_valid_from     timestamp(6),
    after_valid_from      timestamp(6),
    before_valid_until    timestamp(6),
    after_valid_until     timestamp(6),
    reason                varchar(200)
);
CREATE INDEX qwt_idx_resource_grant_audits_grant ON qwt_resource_grant_audits (grant_id, created_at);

-- 门店认领人保持现有能力，后续认领通过改为同事务写 grant。
INSERT INTO qwt_resource_grants (
    deleted, version, subject_user_id, resource_type, resource_id, status, source,
    granted_by, granted_at, created_at, updated_at
)
SELECT false, 0, v.claimed_by, 'VENUE', v.id, 'ACTIVE', 'CLAIM',
       v.claimed_by, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM qwt_venues v
JOIN qwt_users u ON u.id = v.claimed_by AND u.deleted = false
WHERE v.deleted = false AND v.claimed_by IS NOT NULL AND u.role <> 'ADMIN';

INSERT INTO qwt_resource_grant_permissions (grant_id, permission_code)
SELECT g.id, p.permission_code
FROM qwt_resource_grants g
CROSS JOIN (VALUES ('VENUE_PROFILE_EDIT'), ('VENUE_POST_MANAGE'), ('VENUE_PHOTO_DELETE')) p(permission_code)
WHERE g.source = 'CLAIM' AND g.resource_type = 'VENUE';

-- 历史普通用户创建的舞伴保留原资料管理能力；ADMIN 创建记录无需冗余 grant。
INSERT INTO qwt_resource_grants (
    deleted, version, subject_user_id, resource_type, resource_id, status, source,
    granted_by, granted_at, created_at, updated_at
)
SELECT false, 0, d.created_by, 'DANCER', d.id, 'ACTIVE', 'LEGACY_CREATED_BY',
       d.created_by, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM qwt_dancers d
JOIN qwt_users u ON u.id = d.created_by AND u.deleted = false
WHERE d.deleted = false AND u.role <> 'ADMIN';

INSERT INTO qwt_resource_grant_permissions (grant_id, permission_code)
SELECT g.id, p.permission_code
FROM qwt_resource_grants g
CROSS JOIN (VALUES ('DANCER_PROFILE_EDIT'), ('DANCER_MEDIA_MANAGE'),
                   ('DANCER_SERVICE_MANAGE'), ('DANCER_GATE_MANAGE'),
                   ('DANCER_DEMAND_RECORDS_READ')) p(permission_code)
WHERE g.source = 'LEGACY_CREATED_BY' AND g.resource_type = 'DANCER';