-- 门店每日营业快照（信息源自动化更新，2026-08-31 新增）
-- 设计文档：quwuting-ops/venue-opening/README.md（管线侧）
--
-- 语义：信息源（砂舞线报网 / Telegram / 未来渠道）每日发布的「今日营业」是
-- 当日快照，与平台 venue.status（相对持久态）解耦存储：
--   - 快照表只记录「某源声称某店某日营业/休息」的事实（时间序列，可算营业稳定性）；
--   - 长期 status 的反转（CEASED→OPEN）由 DailyOpeningService 按置信度分级把关
--     （仅 EXACT/ALIAS 自动反转，CONTAINED 人工复核——对齐平台「确认态/未经核实」哲学）；
--   - 幂等：同店同日报导源至多一条，重复 apply = upsert 覆盖（created_at 刷新，
--     表示该源当日最新确认时刻，口径同 V59 crowd reports 每日一记）。
--
-- ⚠️ 时间口径（记忆红线，同 V59）：created_at/updated_at 必须由 Java 传入
-- LocalDateTime.now()（JVM 时区=北京时间），禁止用 DB 端 now()——Supabase 会话
-- 时区是 UTC，DB now() 写入 UTC 墙钟，与 JVM 窗口/相对时间比较错位 8h。

CREATE TABLE qwt_venue_daily_openings (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    deleted     boolean NOT NULL,
    venue_id    bigint NOT NULL,
    report_date date NOT NULL,
    source_id   varchar(50) NOT NULL,
    status      varchar(10) NOT NULL,   -- OPEN / CLOSED（信息源语义）
    confidence  varchar(20) NOT NULL    -- EXACT / ALIAS / CONTAINED / FUZZY
);

-- 幂等唯一（部分唯一索引，软删后可重插——对齐全库 deleted 模式）
CREATE UNIQUE INDEX qwt_idx_daily_openings_unique
    ON qwt_venue_daily_openings (venue_id, report_date, source_id)
    WHERE deleted = false;

-- 列表/详情注入「今日营业」：按日期查当日快照（venue_id IN + report_date）
CREATE INDEX qwt_idx_daily_openings_date_venue
    ON qwt_venue_daily_openings (report_date, venue_id);
