-- 门店同步 · 手动映射别名表（2026-08-31 新增）
-- 设计文档：quwuting-ops/venue-opening/README.md（管线侧 Matcher 语义）
--
-- 语义：管理员在 Web 管理后台「门店同步 → 映射管理」手工配置的
-- 「网上门店名称（信息源店名）→ 平台门店」映射，等价于管线 Matcher 的
-- 别名表（ALIAS 置信度命中）。管线 --refresh-aliases 从后端拉取
-- （GET /admin/venue-sync/aliases/export）写入本地 data/aliases.json，
-- 之后匹配时 ALIAS 优先于名称归一化精确匹配。
--   - key = (city, source_name)：城市用标准城市名（对齐 cities.json 口径，
--     如「成都市」），source_name 为信息源清洗后店名（对齐报告 source_name）；
--   - venue_id 指向 qwt_venues.id，配置时后端校验门店存在；
--   - 幂等：同城同名至多一条（部分唯一索引，软删后可重插）；
--   - 软删 deleted 模式对齐全库。
--
-- ⚠️ 时间口径（记忆红线，同 V59/V63）：created_at/updated_at 必须由 Java 传入
-- LocalDateTime.now()（JVM 时区=北京时间），禁止用 DB 端 now()。

CREATE TABLE qwt_venue_sync_aliases (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    deleted     boolean NOT NULL,
    city        varchar(50) NOT NULL,
    source_name varchar(100) NOT NULL,
    venue_id    bigint NOT NULL,
    note        varchar(200) NOT NULL DEFAULT ''
);

-- 幂等唯一（部分唯一索引，软删后可重插——对齐全库 deleted 模式）
CREATE UNIQUE INDEX qwt_idx_sync_aliases_unique
    ON qwt_venue_sync_aliases (city, source_name)
    WHERE deleted = false;

-- 列表展示按最近配置倒序
CREATE INDEX qwt_idx_sync_aliases_updated
    ON qwt_venue_sync_aliases (updated_at);
