-- ============================================================================
-- V7: 舞伴相册照片（照片级"先审后发"审核闸门）
--
-- 背景（2026-08-10，需求：舞伴可上传自己的相册）：
-- 舞伴是真实个人，照片是其真实影像、风险高于场所照片——必须逐张人审后才公开，
-- 与舞伴资料 PENDING 审核同源（先认证、后展示）。venue.photos 是 JSON 数组列
-- （管理员/认领人直写、无逐张审核状态），不适用于舞伴照片，故独立成表。
-- 列定义与 JPA 实体 DancerPhoto 严格一致（Hibernate 物理命名 = 驼峰→下划线）。
-- ============================================================================
CREATE TABLE qwt_dancer_photos (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    deleted    boolean NOT NULL,
    dancer_id  bigint NOT NULL,
    url        varchar(500) NOT NULL,
    status     varchar(20) NOT NULL DEFAULT 'PENDING',
    created_by bigint NOT NULL,
    sort_order integer NOT NULL DEFAULT 0
);
CREATE INDEX qwt_idx_dp_dancer ON qwt_dancer_photos (dancer_id);
CREATE INDEX qwt_idx_dp_dancer_status ON qwt_dancer_photos (dancer_id, status);
CREATE INDEX qwt_idx_dp_status_created ON qwt_dancer_photos (status, created_at);
