-- ============================================================================
-- V9: 积分系统（账户 / 流水 / 每日打卡）
--
-- 背景（2026-08-10 需求设计 V2，见 docs/积分系统-需求设计-V2-2026-08-10.md）：
-- 积分是**资产模型**（账户 + 流水 ledger），与 Reaction（态度表达，每日一记）
-- 完全分离——只在展示层（独立区块）与排名层（热度公式输入项）发生交集。
--
-- 设计要点：
-- 1. qwt_points_accounts：一用户一行（user_id 唯一），balance 为读写快照，
--    earned_total / spent_total 冗余累计——余额高频读（详情页/赠送校验）不 SUM；
-- 2. qwt_points_transactions：**只追加、不可变**的流水，流水是余额对账的
--    唯一事实源（balance_after 快照支持日终 SUM(delta) 对账）；
--    挣取幂等 = 部分唯一索引 (user_id, source_type, source_id) WHERE delta > 0
--    AND source_id IS NOT NULL——同一来源只发一次（打卡 checkin_id / 采纳
--    feedback_id / 管理调整单号），并发/重复请求被 SQLState 23505 兜底；
--    赠送（delta < 0）必带 target_type + target_id，按目标聚合"收到积分"；
-- 3. qwt_daily_checkins：打卡锚点表，UNIQUE(user_id, checkin_date) 保证
--    "一天一次"的业务语义，与流水唯一键（一次打卡只发一次分）职责分离。
--
-- 上报采纳奖励不设每日条数上限（V2 决策）：防刷由管理员采纳人工把关——
-- 奖励只发生在 ADOPTED 终态，而 ADOPTED 是管理员逐条人工判定的结果。
-- ============================================================================

-- ── 积分账户（用户资产，一行一用户） ─────────────────────────────────────
CREATE TABLE qwt_points_accounts (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    user_id      bigint NOT NULL,
    balance      bigint NOT NULL DEFAULT 0,
    earned_total bigint NOT NULL DEFAULT 0,
    spent_total  bigint NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX qwt_uk_points_accounts_user ON qwt_points_accounts (user_id);

-- ── 积分流水（只追加，不可变；余额对账唯一事实源） ────────────────────────
CREATE TABLE qwt_points_transactions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6),
    user_id       bigint NOT NULL,
    delta         bigint NOT NULL,
    balance_after bigint NOT NULL,
    source_type   varchar(30) NOT NULL,
    source_id     bigint,
    target_type   varchar(20),
    target_id     bigint,
    remark        varchar(200)
);
CREATE INDEX qwt_idx_pts_tx_user_created ON qwt_points_transactions (user_id, created_at);
-- 目标聚合（"收到积分"统计 / 热度公式积分项 / 趋势序列，窗口 = created_at）
CREATE INDEX qwt_idx_pts_tx_target ON qwt_points_transactions (target_type, target_id, created_at);
-- 挣取幂等：同一用户同一来源只发一次（source_id 恒非空的挣取场景）
CREATE UNIQUE INDEX qwt_uk_pts_tx_earn_dedup
    ON qwt_points_transactions (user_id, source_type, source_id)
    WHERE delta > 0 AND source_id IS NOT NULL;

-- ── 每日打卡（幂等锚点 + 防刷硬约束） ─────────────────────────────────────
CREATE TABLE qwt_daily_checkins (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6),
    user_id      bigint NOT NULL,
    checkin_date date NOT NULL
);
CREATE INDEX qwt_idx_checkins_user ON qwt_daily_checkins (user_id);
CREATE UNIQUE INDEX qwt_uk_checkins_user_date ON qwt_daily_checkins (user_id, checkin_date);
